/*
    Author: Willi "shukari" Graff
*/

//waituntil {!isnil "ALiVE_autoGeneratedTasks"};
//ALIVE_autoGeneratedTasks = ["MilAssault","MilDefence","CivAssault","Assassination","TransportInsertion","DestroyVehicles","DestroyInfantry","SabotageBuilding","InsurgencyPatrol","InsurgencyDestroyAssets","Rescue","CSAR","CAS","DestroyBuilding","OCA"];
