version: 2
jobs:
  validate-scripts:
    docker:
      - image: acemod/sqflint:latest
    steps:
      - checkout
      - run:
          name: Validate SQF and Config style
          command: python tools/sqf_validator.py && python tools/config_style_checker.py
  linting:
    docker:
      - image: acemod/sqflint:latest
    steps:
      - checkout
      - run:
          name: Lint sqf code
          command: sqflint -d addons || true
