//Fetching classname filters from module and returning them in array
private ["_classModule","_classModuleFilters"];
_classModule = param [0];
_classModuleFilters = [];

_classModuleFilters set[count _classModuleFilters, _classModule getVariable "BLU_CTRG_Cars"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "BLU_CTRG_Helis"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "BLU_CTRG_Men"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "BLU_NATO_Cars"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "BLU_NATO_Tanks"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "BLU_NATO_Helis"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "BLU_NATO_Planes"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "BLU_NATO_Ships"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "BLU_NATO_Men"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "BLU_NATO_Men_SpecialForces"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "BLU_NATO_Men_Divers"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "BLU_FIA_Cars"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "BLU_FIA_Ships"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "BLU_FIA_Men"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "BLU_GEN_Cars"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "BLU_GEN_Men"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "BLU_T_Cars"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "BLU_T_Tanks"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "BLU_T_Helis"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "BLU_T_Planes"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "BLU_T_Ships"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "BLU_T_Men"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "BLU_T_Men_SpecialForces"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "BLU_T_Men_Divers"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "IND_SYN_Cars"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "IND_SYN_Helis"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "IND_SYN_Planes"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "IND_SYN_Ships"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "IND_SYN_Men_Bandits"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "IND_SYN_Men_Paramilitarity"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "IND_AAF_Cars"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "IND_AAF_Tanks"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "IND_AAF_Helis"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "IND_AAF_Planes"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "IND_AAF_Ships"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "IND_AAF_Men"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "IND_AAF_Divers"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "IND_FIA_Cars"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "IND_FIA_Ships"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "IND_FIA_Men"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "OPF_CSAT_Cars"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "OPF_CSAT_Tanks"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "OPF_CSAT_Helis"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "OPF_CSAT_Planes"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "OPF_CSAT_Ships"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "OPF_CSAT_Men"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "OPF_CSAT_Men_Urban"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "OPF_CSAT_Men_SpecialForces"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "OPF_CSAT_Men_Viper"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "OPF_CSAT_Divers"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "OPF_FIA_Cars"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "OPF_FIA_Ships"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "OPF_FIA_Men"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "OPF_T_Cars"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "OPF_T_Tanks"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "OPF_T_Planes"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "OPF_T_Ships"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "OPF_T_Men"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "OPF_T_Men_SpecialForces"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "OPF_T_Men_Viper"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "OPF_T_Divers"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "CIV_Cars"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "CIV_Helis"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "CIV_Planes"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "CIV_Ships"];
_classModuleFilters set[count _classModuleFilters, _classModule getVariable "CIV_Men"];

_classModuleFilters