#include "../script_component.hpp"
/*
    Part of the TBMod ( https://github.com/TacticalBaconDevs/TBMod )
    Developed by http://tacticalbacon.de
*/
private _arsenalType = ACE_player getVariable ["TB_arsenalType", ""];
private _rolle = ACE_player getVariable ["TB_rolle", ""];

if (_arsenalType == "USA") exitWith
{
    private _layout = switch (_rolle) do
    {
        case "lead": {[["rhs_weap_mk18_bk","","","rhsusf_acc_ACOG_RMR",["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",30],[],""],[],["rhs_weap_M320","","","",["3Rnd_Smoke_Grenade_shell_precise",3],[],""],["rhs_uniform_acu_ucp",[["ACE_HuntIR_monitor",1],["ACE_tourniquet",4],["ACE_Flashlight_KSF1",1],["ACE_EntrenchingTool",1],["ACE_CableTie",2]]],["rhsusf_spcs_ucp_teamleader",[["SmokeShell",3,1],["SmokeShellBlue",1,1],["SmokeShellRed",1,1],["3Rnd_Smoke_Grenade_shell_precise",2,3],["ACE_HuntIR_M203",3,1],["TB_rhs_mag_40mm_HE",2,1],["TB_rhs_mag_40mm_HEDP",2,1],["rhs_mag_m713_Red_precise",1,1],["rhs_mag_mk84",3,1]]],["OPXT_ogag_1523",[["ACE_fieldDressing",20],["ACE_adenosine",3],["ACE_atropine",5],["ACE_salineIV",1],["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",12,30]]],"rhsusf_opscore_mar_ut_pelt","",["ACE_Vector","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]};
        case "grena": {[["rhs_weap_mk18_m320","","","rhsusf_acc_ACOG_RMR",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],""],[],[],["rhs_uniform_acu_ucp",[["ACE_tourniquet",4],["ACE_EntrenchingTool",1],["ACE_CableTie",2],["ACE_HuntIR_monitor",1],["ACE_Flashlight_KSF1",1],["ACE_adenosine",3]]],["rhsusf_spcs_ucp_grenadier",[["ACE_fieldDressing",20],["ACE_atropine",5],["ACE_salineIV",1],["ACE_HuntIR_M203",1,1],["rhs_mag_m713_Red_precise",1,1],["TB_rhs_mag_40mm_HEDP",6,1],["TB_rhs_mag_40mm_HE",8,1],["SmokeShell",1,1],["3Rnd_Smoke_Grenade_shell_precise",1,3]]],["rhsusf_assault_eagleaiii_ucp",[["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",10,30],["3Rnd_Smoke_Grenade_shell_precise",1,3],["SmokeShell",1,1],["rhs_mag_mk84",1,1],["TB_rhs_mag_40mm_HE",2,1]]],"rhsusf_opscore_mar_ut_pelt","",["m24_bino","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]};
        case "sani": {[["rhs_weap_mk18_bk","","","rhsusf_acc_ACOG_RMR",["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",30],[],"rhsusf_acc_harris_bipod"],[],[],["rhs_uniform_acu_ucp",[["ACE_surgicalKit",1],["ACE_tourniquet",12],["ACE_EntrenchingTool",1],["ACE_Flashlight_KSF1",1],["ACE_CableTie",2]]],["rhsusf_spcs_ucp_medic",[["adv_aceCPR_AED",1],["ACE_quikclot",20],["SmokeShell",2,1],["rhs_mag_mk84",2,1],["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",7,30]]],["B_Kitbag_cbr",[["ACE_plasmaIV",4],["ACE_plasmaIV_500",6],["ACE_elasticBandage",40],["ACE_packingBandage",40],["ACE_adenosine",6],["ACE_atropine",12],["ACE_morphine",5],["ACE_epinephrine",5],["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",3,30]]],"rhsusf_opscore_mar_ut_pelt","",["m24_bino","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]};
        case "mg": {[["rhs_weap_m249_light_S","","","rhsusf_acc_ACOG_RMR",["rhsusf_200Rnd_556x45_M855_mixed_soft_pouch_ucp",200],[],"rhsusf_acc_saw_lw_bipod"],[],[],["rhs_uniform_acu_ucp",[["ACE_CableTie",2],["ACE_EntrenchingTool",1],["ACE_Flashlight_KSF1",1],["ACE_tourniquet",4],["ACE_RangeCard",1],["ACE_adenosine",3],["ACE_atropine",5],["ACE_fieldDressing",14]]],["rhsusf_iotv_ucp_SAW",[["ACE_fieldDressing",6],["ACE_salineIV",1],["rhsusf_200Rnd_556x45_M855_mixed_soft_pouch_ucp",2,200],["SmokeShell",2,1],["rhs_mag_mk84",1,1]]],["rhsusf_assault_eagleaiii_ucp",[["rhsusf_200Rnd_556x45_M855_mixed_soft_pouch_ucp",3,200]]],"rhsusf_opscore_mar_ut_pelt","",["m24_bino","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]};
        case "spreng": {[["rhs_weap_mk18_KAC","","","rhsusf_acc_ACOG_RMR",["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",30],[],"rhsusf_acc_harris_bipod"],[],["ACE_VMM3","","","",[],[],""],["rhs_uniform_acu_ucp",[["ACE_wirecutter",1],["ACE_DefusalKit",1],["ACE_EntrenchingTool",1]]],["rhsusf_spcs_ucp_rifleman",[["ACE_tourniquet",4],["ACE_M26_Clacker",1],["ACE_Flashlight_KSF1",1],["ACE_CableTie",2],["SmokeShell",2,1],["rhs_mag_mk84",2,1],["DemoCharge_Remote_Mag",4,1]]],["B_Kitbag_cbr",[["ToolKit",1],["ACE_salineIV",1],["ACE_fieldDressing",20],["ACE_adenosine",3],["ACE_atropine",5],["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",10,30]]],"rhsusf_opscore_mar_ut_pelt","",["m24_bino","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]};
        case "aaat": {[["rhs_weap_mk18_bk","","","rhsusf_acc_ACOG_RMR",["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",30],[],"rhsusf_acc_harris_bipod"],["rhs_weap_maaws","","","",["rhs_mag_maaws_HEAT",1],[],""],[],["rhs_uniform_acu_ucp",[["ACE_adenosine",3],["ACE_tourniquet",4],["ACE_atropine",5],["ACE_Flashlight_KSF1",1],["ACE_CableTie",2],["ACE_EntrenchingTool",1],["ACE_fieldDressing",15]]],["rhsusf_spcs_ucp_saw",[["ACE_salineIV",1],["ACE_fieldDressing",5],["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",8,30],["SmokeShell",2,1],["rhs_mag_mk84",1,1]]],["B_Carryall_mcamo",[["rhs_mag_maaws_HEAT",2,1],["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",2,30]]],"rhsusf_opscore_mar_ut_pelt","",["m24_bino","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]};
        case "trag": {[["rhs_weap_mk18_bk","","","rhsusf_acc_ACOG_RMR",["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",30],[],"rhsusf_acc_harris_bipod"],["TB_rhs_weap_M136_CS","","","",["rhs_m136_mag",1],[],""],[],["rhs_uniform_acu_ucp",[["ACE_EntrenchingTool",1],["ACE_tourniquet",4],["ACE_Flashlight_KSF1",1],["ACE_CableTie",2],["ACE_adenosine",3],["ACE_atropine",5],["ACE_salineIV",1],["ACE_fieldDressing",5]]],["rhsusf_spcs_ucp_machinegunner",[["ACE_fieldDressing",15],["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",11,30],["SmokeShell",3,1],["SmokeShellBlue",1,1],["rhs_mag_mk84",1,1]]],["B_Carryall_mcamo",[["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",19,30]]],"rhsusf_opscore_mar_ut_pelt","",["ACE_Vector","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]};
        case "pilot": {[["rhsusf_weap_MP7A2","","","",["rhsusf_mag_40Rnd_46x30_FMJ",40],[],""],[],["rhsusf_weap_glock17g4","rhsusf_acc_omega9k","acc_flashlight_pistol","",["rhsusf_mag_17Rnd_9x19_FMJ",17],[],""],["U_B_PilotCoveralls",[["adv_aceCPR_AED",1],["ACE_surgicalKit",1],["ACE_Flashlight_KSF1",1],["ACE_tourniquet",8]]],["rhsusf_spcs_ucp",[["ACE_quikclot",20],["rhsusf_mag_40Rnd_46x30_FMJ",6,40],["SmokeShellBlue",2,1],["SmokeShellRed",2,1],["SmokeShell",2,1],["ACE_Chemlight_IR",2,1],["rhsusf_mag_17Rnd_9x19_FMJ",4,17],["ACE_Chemlight_HiYellow",2,1]]],["OPXT_ogag_1523",[["ACE_elasticBandage",10],["ACE_morphine",1],["ACE_adenosine",3],["ACE_epinephrine",2],["ACE_atropine",5],["ACE_packingBandage",10],["ACE_plasmaIV_500",4],["ACE_quikclot",20],["ToolKit",1]]],"H_PilotHelmetFighter_B","",[],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "sniper": {[["rhs_weap_M107","","","rhsusf_acc_premier",["rhsusf_mag_10Rnd_STD_50BMG_M33",10],[],""],[],[],["U_B_FullGhillie_sard",[["ACE_Flashlight_KSF1",1],["ACE_ATragMX",1],["ACE_RangeCard",1],["ACE_CableTie",2],["ACE_MapTools",1],["ACE_Kestrel4500",1],["ACE_tourniquet",4],["ACE_fieldDressing",20],["ACE_adenosine",3],["ACE_atropine",5],["ACE_Chemlight_IR",2,1],["SmokeShell",2,1],["SmokeShellBlue",1,1]]],["rhsusf_mbav_rifleman",[["rhsusf_mag_10Rnd_STD_50BMG_M33",4,10],["rhsusf_mag_10Rnd_STD_50BMG_mk211",2,10],["SmokeShellRed",1,1]]],["OPXT_oga_1523",[["ACE_Tripod",1],["rhsusf_mag_10Rnd_STD_50BMG_M33",2,10],["rhsusf_mag_10Rnd_STD_50BMG_mk211",3,10]]],"rhsusf_opscore_mar_ut_pelt","",["ACE_Vector","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]};
        case "spotter": {[["rhs_weap_mk18_m320","rhsusf_acc_nt4_black","","rhsusf_acc_ACOG_RMR",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],["TB_rhs_mag_40mm_IR_Grenade",1],""],[],[],["U_B_FullGhillie_sard",[["ACE_HuntIR_monitor",1],["ACE_RangeCard",1],["ACE_ATragMX",1],["ACE_Kestrel4500",1],["ACE_Flashlight_KSF1",1],["ACE_tourniquet",4],["ACE_CableTie",2],["ACE_adenosine",3],["ACE_atropine",5],["ACE_fieldDressing",20]]],["rhsusf_mbav_grenadier",[["3Rnd_Smoke_Grenade_shell_precise",1,3],["TB_rhs_mag_40mm_HEDP",2,1],["TB_rhs_mag_40mm_HE",4,1],["ACE_HuntIR_M203",1,1],["rhs_mag_30Rnd_556x45_M855A1_PMAG",8,30],["SmokeShell",2,1],["SmokeShellBlue",1,1],["SmokeShellRed",1,1]]],["OPXT_oga_1523",[["ACE_salineIV",2],["rhsusf_mag_10Rnd_STD_50BMG_M33",2,10],["rhsusf_mag_10Rnd_STD_50BMG_mk211",1,10],["rhs_mag_30Rnd_556x45_M855A1_PMAG",2,30]]],"rhsusf_opscore_mar_ut_pelt","",["Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "jtac": {[["rhs_weap_mk18_KAC","","","rhsusf_acc_ACOG_RMR",["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",30],[],"rhsusf_acc_harris_bipod"],[],[],["rhs_uniform_acu_ucp",[["ACE_UAVBattery",1],["ACE_tourniquet",4],["ACE_CableTie",2],["ACE_Flashlight_KSF1",1],["ACE_EntrenchingTool",1],["ACE_adenosine",3]]],["rhsusf_spcs_ucp_rifleman",[["ACE_salineIV",1],["ACE_fieldDressing",10],["ACE_atropine",5],["SmokeShell",2,1],["SmokeShellBlue",1,1],["SmokeShellRed",1,1],["rhs_mag_mk84",2,1],["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",8,30]]],["B_UAV_01_backpack_F",[]],"rhsusf_opscore_mar_ut_pelt","",["Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","B_UavTerminal","TFAR_anprc152","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]};
        case "arzt": {[["rhsusf_weap_MP7A2","","","",["rhsusf_mag_40Rnd_46x30_FMJ",40],[],"rhsusf_acc_grip2"],[],[],["rhs_uniform_acu_ucp",[["ACE_surgicalKit",1],["ACE_tourniquet",16],["ACE_Flashlight_KSF1",1],["ACE_CableTie",2]]],["rhsusf_spcs_ucp_medic",[["adv_aceCPR_AED",1],["ACE_quikclot",30],["rhsusf_mag_40Rnd_46x30_FMJ",4,40],["SmokeShell",2,1],["SmokeShellRed",1,1],["SmokeShellBlue",1,1],["rhs_mag_mk84",1,1]]],["B_Kitbag_cbr",[["ACE_bloodIV",5],["ACE_bloodIV_500",3],["ACE_bloodIV_250",6],["ACE_adenosine",15],["ACE_epinephrine",10],["ACE_morphine",10],["ACE_elasticBandage",60],["ACE_packingBandage",60],["ACE_atropine",20]]],"rhsusf_opscore_mar_ut_pelt","",["m24_bino","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]};
        case "rifle" : {[["rhs_weap_mk17_STD","","","rhsusf_acc_ACOG_RMR",["rhs_mag_20Rnd_SCAR_762x51_mk316_special",20],[],"rhsusf_acc_harris_bipod"],[],[],["rhs_uniform_acu_ucp",[["ACE_tourniquet",4],["ACE_Flashlight_KSF1",1],["ACE_EntrenchingTool",1],["ACE_CableTie",2],["ACE_fieldDressing",20],["ACE_adenosine",3]]],["rhsusf_spcs_ucp_rifleman",[["ACE_atropine",5],["ACE_salineIV",1],["SmokeShell",2,1],["rhs_mag_mk84",2,1],["rhs_mag_20Rnd_SCAR_762x51_mk316_special",1,20]]],["B_TacticalPack_blk",[["rhs_mag_20Rnd_SCAR_762x51_mk316_special",5,20]]],"rhsusf_opscore_mar_ut_pelt","",["ACE_Vector","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]};
        case "pionier" : {[["rhs_weap_mk18_bk","","","rhsusf_acc_ACOG_RMR",["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",30],[],"rhsusf_acc_harris_bipod"],[],["ACE_VMM3","","","",[],[],""],["rhs_uniform_acu_ucp",[["ACE_tourniquet",4],["ACE_EntrenchingTool",1],["ACE_wirecutter",1],["ACE_adenosine",1]]],["rhsusf_spcs_ucp_rifleman",[["ACE_DefusalKit",1],["ACE_CableTie",2],["ACE_fieldDressing",20],["ACE_adenosine",2],["ACE_atropine",5],["ACE_salineIV",1],["SmokeShell",2,1],["rhs_mag_mk84",1,1]]],["B_Kitbag_cbr",[["ToolKit",1],["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",10,30]]],"rhsusf_opscore_mar_ut_pelt","",["m24_bino","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]};
        default {[]};
    };

    ACE_player setUnitLoadout [_layout, true];
};

if (_arsenalType == "UK") exitWith
{
    private _layout = switch (_rolle) do
    {
        case "lead": {[["UK3CB_BAF_L85A2_RIS","","","RKSL_optic_RMR_RM33",["UK3CB_BAF_556_30Rnd",30],[],""],[],["rhs_weap_M320","","","",["ACE_HuntIR_M203",1],[],""],["UK3CB_BAF_U_CombatUniform_DDPM_ShortSleeve",[["ACE_MapTools",1],["ACE_HuntIR_monitor",1],["ACE_Flashlight_KSF1",1],["ACE_CableTie",5],["ACE_microDAGR",1],["ACE_salineIV",1],["ACE_adenosine",1]]],["UK3CB_BAF_V_Osprey_DDPM8",[["ACE_fieldDressing",30],["ACE_atropine",7],["SmokeShell",5,1],["SmokeShellBlue",2,1],["SmokeShellGreen",2,1],["SmokeShellRed",2,1],["TB_rhs_mag_40mm_HE",4,1],["ACE_HuntIR_M203",4,1],["3Rnd_Smoke_Grenade_shell_precise",1,3]]],["UK3CB_BAF_B_Bergen_DDPM_JTAC_H_A",[["ACE_tourniquet",4],["UK3CB_BAF_556_30Rnd_T",9,30]]],"UK3CB_BAF_H_Mk6_DDPM_A","",["Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "grena": {[["UK3CB_BAF_L85A2_UGL_HWS","","UK3CB_BAF_LLM_Flashlight_Black","RKSL_optic_EOT552",["UK3CB_BAF_556_30Rnd_T",30],["3Rnd_Smoke_Grenade_shell_precise",3],""],[],["UK3CB_BAF_L9A1","","","",["30Rnd_9x21_Green_Mag",30],[],""],["UK3CB_BAF_U_CombatUniform_DDPM_ShortSleeve",[["ACE_MapTools",1],["ACE_HuntIR_monitor",1],["ACE_Flashlight_KSF1",1],["ACE_CableTie",5],["ACE_salineIV",1],["ACE_adenosine",1]]],["UK3CB_BAF_V_Osprey_DDPM3",[["ACE_fieldDressing",30],["ACE_atropine",7],["3Rnd_Smoke_Grenade_shell_precise",2,3],["TB_rhs_mag_40mm_HE",11,1],["ACE_HuntIR_M203",2,1]]],["UK3CB_BAF_B_Kitbag_TAN",[["ACE_tourniquet",4],["UK3CB_BAF_556_30Rnd_T",10,30],["TB_rhs_mag_40mm_Slugshot",5,1],["TB_rhs_mag_40mm_HEDP",5,1]]],"UK3CB_BAF_H_Mk6_DDPM_A","",["m24_bino","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "arzt": {[[],[],[],["UK3CB_BAF_U_CombatUniform_DDPM_ShortSleeve",[["ACE_MapTools",1],["ACE_Flashlight_KSF1",1],["ACE_CableTie",5],["ACE_salineIV",1],["ACE_adenosine",1]]],[],[],"UK3CB_BAF_H_Mk6_DDPM_A","",[],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "sani": {[["UK3CB_BAF_L85A2_RIS_Tan","","UK3CB_BAF_LLM_Flashlight_Black","RKSL_optic_EOT552",["UK3CB_BAF_556_30Rnd_T",30],[],""],[],[],["UK3CB_BAF_U_CombatUniform_DDPM_ShortSleeve",[["ACE_surgicalKit",1],["ACE_CableTie",5],["ACE_MapTools",1],["ACE_Flashlight_KSF1",1],["ACE_adenosine",5],["ACE_epinephrine",6],["ACE_morphine",6]]],["UK3CB_BAF_V_Osprey_DDPM1",[["ACE_quikclot",30],["ACE_packingBandage",40],["ACE_elasticBandage",50],["ACE_atropine",10],["ACE_EntrenchingTool",1]]],["UK3CB_BAF_B_Kitbag_TAN",[["adv_aceCPR_AED",1],["ACE_plasmaIV",10],["ACE_plasmaIV_500",10],["ACE_plasmaIV_250",5],["UK3CB_BAF_556_30Rnd_T",8,30]]],"UK3CB_BAF_H_Mk6_DDPM_A","",["m24_bino","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "mg": {[["UK3CB_BAF_L110A3","","","",["UK3CB_BAF_556_200Rnd",200],[],""],[],["UK3CB_BAF_L9A1","","","",["UK3CB_BAF_9_13Rnd",13],[],""],["UK3CB_BAF_U_CombatUniform_DDPM_ShortSleeve",[["ACE_MapTools",1],["ACE_Flashlight_KSF1",1],["ACE_CableTie",5],["ACE_salineIV",1],["ACE_adenosine",1],["ACE_RangeCard",1],["ACE_EntrenchingTool",1]]],["UK3CB_BAF_V_Osprey_DDPM8",[["ACE_fieldDressing",30],["ACE_atropine",7],["SmokeShell",5,1]]],["UK3CB_BAF_B_Kitbag_DDPM",[["ACE_tourniquet",4],["UK3CB_BAF_556_200Rnd_T",3,200],["30Rnd_9x21_Green_Mag",2,30]]],"UK3CB_BAF_H_Mk6_DDPM_A","",["m24_bino","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "spreng": {[["UK3CB_BAF_L85A2_RIS_Tan","","UK3CB_BAF_LLM_Flashlight_Black","RKSL_optic_RMR_RM33",["UK3CB_BAF_556_30Rnd",30],[],""],[],["ACE_VMM3","","","",[],[],""],["UK3CB_BAF_U_CombatUniform_DDPM_ShortSleeve",[["ACE_MapTools",1],["ACE_Flashlight_KSF1",1],["ACE_CableTie",5],["ACE_salineIV",1],["ACE_adenosine",1],["ACE_EntrenchingTool",1],["ACE_M26_Clacker",1],["ACE_DeadManSwitch",1],["ACE_DefusalKit",1]]],["UK3CB_BAF_V_Osprey_DDPM5",[["ACE_fieldDressing",30],["ACE_atropine",7],["DemoCharge_Remote_Mag",4,1]]],["UK3CB_BAF_B_Kitbag_TAN",[["ToolKit",1],["ACE_wirecutter",1],["SmokeShell",5,1],["SatchelCharge_Remote_Mag",1,1],["UK3CB_BAF_556_30Rnd_T",7,30]]],"UK3CB_BAF_H_Mk6_DDPM_A","",[],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "aaat": {[["UK3CB_BAF_L85A2_RIS_Tan","","UK3CB_BAF_LLM_Flashlight_Black","RKSL_optic_RMR_RM33",["UK3CB_BAF_556_30Rnd_T",30],[],""],["rhs_weap_maaws","","","",["rhs_mag_maaws_HEAT",1],[],""],["UK3CB_BAF_L9A1","","","",["UK3CB_BAF_9_13Rnd",13],[],""],["UK3CB_BAF_U_CombatUniform_DDPM_ShortSleeve",[["ACE_MapTools",1],["ACE_Flashlight_KSF1",1],["ACE_CableTie",5],["ACE_salineIV",1],["ACE_adenosine",1],["ACE_EntrenchingTool",1]]],["UK3CB_BAF_V_Osprey_DDPM2",[["ACE_fieldDressing",30],["ACE_atropine",7],["UK3CB_BAF_556_30Rnd_T",7,30]]],["UK3CB_BAF_B_Carryall_DDPM",[["rhs_mag_maaws_HEAT",2,1],["rhs_mag_maaws_HE",1,1],["SmokeShell",5,1]]],"UK3CB_BAF_H_Mk6_DDPM_A","",[],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "trag": {[["UK3CB_BAF_L85A2_RIS_Tan","","","RKSL_optic_RMR_RM33",["UK3CB_BAF_556_30Rnd",30],[],""],[],[],["UK3CB_BAF_U_CombatUniform_DDPM_ShortSleeve",[["ACE_MapTools",1],["ACE_Flashlight_KSF1",1],["ACE_CableTie",5],["ACE_salineIV",1],["ACE_adenosine",1],["ACE_EntrenchingTool",1]]],["UK3CB_BAF_V_Osprey_DDPM5",[["ACE_fieldDressing",30],["ACE_atropine",7],["SmokeShell",5,1],["UK3CB_BAF_556_30Rnd_T",8,30]]],["UK3CB_BAF_B_Carryall_DDPM",[["ACE_tourniquet",4],["UK3CB_BAF_556_200Rnd_T",2,200],["UK3CB_BAF_556_30Rnd_T",17,30]]],"UK3CB_BAF_H_Mk6_DDPM_A","",["ACE_Vector","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "dmr": {[]};
        case "pilot": {[["UK3CB_BAF_L91A1","","","",["UK3CB_BAF_9_30Rnd",30],[],""],[],[],["UK3CB_BAF_U_CombatUniform_DDPM_ShortSleeve",[["ACE_MapTools",1],["ACE_Flashlight_KSF1",1],["ACE_CableTie",5],["ACE_salineIV",1],["ACE_adenosine",1],["ACE_surgicalKit",1],["ACE_tourniquet",7]]],["UK3CB_BAF_V_Osprey_DDPM1",[["ACE_quikclot",30],["ACE_elasticBandage",40],["ACE_packingBandage",40],["adv_aceCPR_AED",1]]],["UK3CB_BAF_B_Bergen_DDPM_JTAC_H_A",[["ACE_epinephrine",8],["ACE_morphine",8],["ACE_atropine",10],["ACE_adenosine",5],["ToolKit",1],["ACE_bodyBag",2],["UK3CB_BAF_9_30Rnd",7,30]]],"H_PilotHelmetFighter_B","",["m24_bino","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "sniper": {[[],[],[],["UK3CB_BAF_U_CombatUniform_DDPM_ShortSleeve",[["ACE_MapTools",1],["ACE_Flashlight_KSF1",1],["ACE_CableTie",5],["ACE_salineIV",1],["ACE_adenosine",1]]],[],[],"UK3CB_BAF_H_Mk6_DDPM_A","",[],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "spotter": {[[],[],[],["UK3CB_BAF_U_CombatUniform_DDPM_ShortSleeve",[["ACE_MapTools",1],["ACE_Flashlight_KSF1",1],["ACE_CableTie",5],["ACE_salineIV",1],["ACE_adenosine",1]]],[],[],"UK3CB_BAF_H_Mk6_DDPM_A","",[],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "jtac": {[[],[],[],["UK3CB_BAF_U_CombatUniform_DDPM_ShortSleeve",[["ACE_MapTools",1],["ACE_Flashlight_KSF1",1],["ACE_CableTie",5],["ACE_salineIV",1],["ACE_adenosine",1]]],[],[],"UK3CB_BAF_H_Mk6_DDPM_A","",[],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "rifle" : {[["rhs_weap_mk17_CQC","","UK3CB_BAF_LLM_Flashlight_Black","RKSL_optic_LDS_PiP",["rhs_mag_20Rnd_SCAR_762x51_m62_tracer",20],[],""],[],[],["UK3CB_BAF_U_CombatUniform_DDPM_ShortSleeve",[["ACE_MapTools",1],["ACE_Flashlight_KSF1",1],["ACE_CableTie",5],["ACE_salineIV",1],["ACE_adenosine",1],["ACE_EntrenchingTool",1]]],["UK3CB_BAF_V_Osprey_DDPM5",[["ACE_fieldDressing",30],["ACE_atropine",8],["AMP_Breaching_Charge_Mag",5,1]]],["UK3CB_BAF_B_Kitbag_TAN",[["ACE_tourniquet",4],["rhs_mag_20Rnd_SCAR_762x51_m62_tracer",9,20],["SmokeShell",6,1]]],"UK3CB_BAF_H_Mk6_DDPM_A","",["m24_bino","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "pionier" : {[["UK3CB_BAF_L85A2_RIS_Tan","","UK3CB_BAF_LLM_Flashlight_Black","RKSL_optic_RMR_RM33",["UK3CB_BAF_556_30Rnd",30],[],""],[],["ACE_VMM3","","","",[],[],""],["UK3CB_BAF_U_CombatUniform_DDPM_ShortSleeve",[["ACE_MapTools",1],["ACE_Flashlight_KSF1",1],["ACE_CableTie",5],["ACE_salineIV",1],["ACE_adenosine",1],["ACE_EntrenchingTool",1],["ACE_DefusalKit",1]]],["UK3CB_BAF_V_Osprey_DDPM5",[["ACE_fieldDressing",30],["ACE_atropine",7],["UK3CB_BAF_556_30Rnd_T",6,30]]],["UK3CB_BAF_B_Bergen_DDPM_JTAC_H_A",[["ToolKit",1],["ACE_tourniquet",5],["ACE_wirecutter",1],["SmokeShell",5,1],["UK3CB_BAF_556_30Rnd_T",7,30]]],"UK3CB_BAF_H_Mk6_DDPM_A","",["m24_bino","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        default {[]};
    };

    ACE_player setUnitLoadout [_layout, true];
};

if (_arsenalType == "BW") exitWith
{
    private _layout = switch (_rolle) do
    {
        case "lead": {[["BWA3_G38","","BWA3_acc_VarioRay_irlaser_black","BWA3_optic_ZO4x30i_MicroT2_pip",["BWA3_30Rnd_556x45_G36_Tracer",30],[],"BWA3_bipod_Harris"],[],[],["BWA3_Uniform2_Fleck",[["ACE_tourniquet",4],["ACE_HuntIR_monitor",1],["ACE_CableTie",5],["ACE_EntrenchingTool",1],["ACE_Flashlight_KSF1",1]]],["BWA3_Vest_Leader_Fleck",[["BWA3_DM25",5,1],["BWA3_DM32_Red",2,1],["BWA3_DM32_Green",2,1],["BWA3_30Rnd_556x45_G36_Tracer",12,30]]],["OPXT_pen_grz_1523",[["ACE_salineIV",2],["ACE_adenosine",5],["ACE_fieldDressing",30],["ACE_atropine",5]]],"BWA3_OpsCore_Fleck_Camera","",["BWA3_Vector","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "grena": {[["BWA3_G38_AG40","","BWA3_acc_VarioRay_irlaser_black","BWA3_optic_ZO4x30i_MicroT2_pip",["BWA3_30Rnd_556x45_G36_Tracer",30],["1Rnd_HE_Grenade_shell",1],""],[],[],["BWA3_Uniform2_Fleck",[["ACE_tourniquet",4],["ACE_HuntIR_monitor",1],["ACE_CableTie",5],["ACE_EntrenchingTool",1],["ACE_Flashlight_KSF1",1]]],["BWA3_Vest_Leader_Fleck",[["BWA3_DM25",5,1],["BWA3_DM32_Red",2,1],["BWA3_DM32_Green",2,1],["1Rnd_HE_Grenade_shell",15,1],["1Rnd_Smoke_Grenade_shell",6,1],["ACE_HuntIR_M203",5,1]]],["BWA3_Kitbag_Fleck",[["ACE_fieldDressing",30],["ACE_adenosine",5],["ACE_atropine",5],["ACE_salineIV",2],["BWA3_30Rnd_556x45_G36_Tracer",15,30]]],"BWA3_OpsCore_Fleck_Camera","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "sani": {[["BWA3_G38","","BWA3_acc_VarioRay_irlaser_black","BWA3_optic_ZO4x30i_MicroT2_pip",["BWA3_30Rnd_556x45_G36_Tracer",30],[],"BWA3_bipod_Harris"],[],[],["BWA3_Uniform2_Fleck",[["ACE_tourniquet",9],["ACE_CableTie",4],["ACE_EntrenchingTool",1],["ACE_Flashlight_KSF1",1],["ACE_surgicalKit",1]]],["BWA3_Vest_Leader_Fleck",[["ACE_plasmaIV",5],["ACE_plasmaIV_500",5],["ACE_adenosine",7],["ACE_atropine",10],["ACE_morphine",5],["ACE_epinephrine",7],["BWA3_DM25",5,1],["BWA3_DM32_Red",2,1],["BWA3_DM32_Green",2,1]]],["BWA3_Kitbag_Fleck_Medic",[["ACE_elasticBandage",35],["ACE_packingBandage",45],["adv_aceCPR_AED",1],["ACE_quikclot",20],["BWA3_30Rnd_556x45_G36_Tracer",15,30]]],"BWA3_OpsCore_Fleck_Camera","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "mg": {[["BWA3_MG4","","BWA3_acc_VarioRay_irlaser_black","BWA3_optic_ZO4x30i_MicroT2",["BWA3_200Rnd_556x45_Tracer",200],[],""],[],[],["BWA3_Uniform2_Fleck",[["ACE_CableTie",5],["ACE_EntrenchingTool",1],["ACE_Flashlight_KSF1",1],["ACE_tourniquet",4]]],["BWA3_Vest_Leader_Fleck",[["BWA3_DM25",5,1],["BWA3_DM32_Red",2,1],["BWA3_DM32_Green",2,1],["BWA3_200Rnd_556x45_Tracer",2,200]]],["BWA3_PatrolPack_Fleck",[["ACE_fieldDressing",30],["ACE_adenosine",5],["ACE_atropine",5],["BWA3_200Rnd_556x45_Tracer",4,200]]],"BWA3_OpsCore_Fleck_Camera","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "spreng": {[["BWA3_G38","","BWA3_acc_VarioRay_irlaser_black","BWA3_optic_ZO4x30i_MicroT2",["BWA3_30Rnd_556x45_G36_Tracer",30],[],"BWA3_bipod_Harris"],[],[],["BWA3_Uniform2_Fleck",[["ACE_EntrenchingTool",1],["ACE_Flashlight_KSF1",1],["ACE_tourniquet",4],["ACE_wirecutter",1]]],["BWA3_Vest_Leader_Fleck",[["ACE_CableTie",5],["ACE_DefusalKit",1],["BWA3_DM25",5,1],["BWA3_DM32_Red",2,1],["BWA3_DM32_Green",2,1],["DemoCharge_Remote_Mag",4,1]]],["BWA3_PatrolPack_Fleck",[["ACE_fieldDressing",30],["ACE_adenosine",5],["ACE_atropine",5],["SatchelCharge_Remote_Mag",2,1],["BWA3_30Rnd_556x45_G36_Tracer",10,30]]],"BWA3_OpsCore_Fleck_Camera","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "aaat": {[["BWA3_G38","","BWA3_acc_VarioRay_irlaser_black","BWA3_optic_ZO4x30i_MicroT2",["BWA3_30Rnd_556x45_G36_Tracer",30],[],"BWA3_bipod_Harris"],["BWA3_CarlGustav","","","BWA3_optic_CarlGustav",["BWA3_CarlGustav_HEAT",1],[],""],[],["BWA3_Uniform2_Fleck",[["ACE_tourniquet",4],["ACE_CableTie",5],["ACE_EntrenchingTool",1],["ACE_Flashlight_KSF1",1]]],["BWA3_Vest_Leader_Fleck",[["BWA3_DM25",5,1],["BWA3_DM32_Red",2,1],["BWA3_DM32_Green",2,1],["BWA3_30Rnd_556x45_G36_Tracer",12,30]]],["BWA3_PatrolPack_Fleck",[["ACE_salineIV",2],["ACE_adenosine",5],["ACE_fieldDressing",30],["ACE_atropine",5],["BWA3_CarlGustav_HEAT",3,1]]],"BWA3_OpsCore_Fleck_Camera","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "trag": {[["BWA3_G38","","BWA3_acc_VarioRay_irlaser_black","BWA3_optic_ZO4x30i_MicroT2",["BWA3_30Rnd_556x45_G36_Tracer",30],[],"BWA3_bipod_Harris"],[],[],["BWA3_Uniform2_Fleck",[["ACE_tourniquet",4],["ACE_CableTie",5],["ACE_EntrenchingTool",1],["ACE_Flashlight_KSF1",1]]],["BWA3_Vest_Leader_Fleck",[["BWA3_DM25",5,1],["BWA3_DM32_Red",2,1],["BWA3_DM32_Green",2,1],["BWA3_30Rnd_556x45_G36_Tracer",12,30]]],["BWA3_PatrolPack_Fleck",[["ACE_salineIV",2],["ACE_adenosine",5],["ACE_fieldDressing",30],["ACE_atropine",5],["BWA3_CarlGustav_HEAT",1,1],["BWA3_200Rnd_556x45_Tracer",2,200],["BWA3_30Rnd_556x45_G36_Tracer",12,30]]],"BWA3_OpsCore_Fleck_Camera","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "pilot": {[[],[],["BWA3_MP7","BWA3_muzzle_snds_Rotex_II","BWA3_acc_VarioRay_irlaser_black","BWA3_optic_EOTech552",["BWA3_40Rnd_46x30_MP7",40],[],""],["BWA3_Uniform2_Fleck",[["ACE_tourniquet",4],["ACE_CableTie",5],["ACE_EntrenchingTool",1],["ACE_Flashlight_KSF1",1]]],["BWA3_Vest_Leader_Fleck",[["ACE_morphine",5],["ACE_epinephrine",5],["adv_aceCPR_AED",1],["ACE_surgicalKit",1],["BWA3_DM25",5,1],["BWA3_DM32_Red",2,1],["BWA3_DM32_Green",2,1]]],["OPXT_at_ix_1523",[["ACE_atropine",5],["ACE_adenosine",5],["ACE_plasmaIV",5],["ACE_plasmaIV_500",5],["ACE_elasticBandage",40],["ACE_packingBandage",35]]],"BWA3_Knighthelm","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "sniper": {[["BWA3_G82","","","BWA3_optic_M5Xi_MSR_pip",[],[],""],[],[],["BWA3_Uniform2_Fleck",[["ACE_tourniquet",4],["ACE_HuntIR_monitor",1],["ACE_CableTie",5],["ACE_EntrenchingTool",1],["ACE_Flashlight_KSF1",1]]],["BWA3_Vest_Leader_Fleck",[["BWA3_DM25",5,1],["BWA3_DM32_Red",2,1],["BWA3_DM32_Green",2,1]]],["OPXT_pen_grz_1523",[["ACE_salineIV",2],["ACE_adenosine",5],["ACE_fieldDressing",30],["ACE_atropine",5]]],"BWA3_OpsCore_Fleck_Camera","",["ACE_VectorDay","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "spotter": {[["BWA3_G38_AG40","","BWA3_acc_VarioRay_irlaser_black","",["BWA3_30Rnd_556x45_G36_Tracer",30],["1Rnd_HE_Grenade_shell",1],""],[],[],["BWA3_Uniform2_Fleck",[["ACE_tourniquet",4],["ACE_HuntIR_monitor",1],["ACE_CableTie",5],["ACE_EntrenchingTool",1],["ACE_Flashlight_KSF1",1]]],["BWA3_Vest_Leader_Fleck",[["ACE_Tripod",1],["ACE_Sandbag_empty",1],["BWA3_DM25",5,1],["BWA3_DM32_Red",2,1],["BWA3_DM32_Green",2,1],["1Rnd_Smoke_Grenade_shell",6,1],["ACE_HuntIR_M203",5,1]]],["OPXT_ogao_1523",[["ACE_fieldDressing",30],["ACE_adenosine",5],["ACE_atropine",5],["ACE_salineIV",2],["BWA3_30Rnd_556x45_G36_Tracer",12,30]]],"BWA3_OpsCore_Fleck_Camera","",["ACE_VectorDay","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "jtac": {[["BWA3_G38","","BWA3_acc_VarioRay_irlaser_black","BWA3_optic_ZO4x30i_MicroT2",["BWA3_30Rnd_556x45_G36_Tracer",30],[],"BWA3_bipod_Harris"],[],[],["BWA3_Uniform2_Fleck",[["ACE_EntrenchingTool",1],["ACE_Flashlight_KSF1",1],["ACE_tourniquet",4],["ACE_CableTie",5]]],["BWA3_Vest_Leader_Fleck",[["ACE_fieldDressing",20],["ACE_adenosine",5],["ACE_atropine",5],["BWA3_30Rnd_556x45_G36_Tracer",10,30]]],["B_UAV_01_backpack_F",[]],"BWA3_OpsCore_Fleck_Camera","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "arzt": {[[],[],["BWA3_MP7","","","BWA3_optic_EOTech",["BWA3_40Rnd_46x30_MP7",40],[],""],["BWA3_Uniform2_Fleck",[["ACE_tourniquet",9],["ACE_CableTie",4],["ACE_EntrenchingTool",1],["ACE_Flashlight_KSF1",1],["ACE_surgicalKit",1]]],["BWA3_Vest_Leader_Fleck",[["ACE_adenosine",7],["ACE_atropine",10],["ACE_morphine",5],["ACE_epinephrine",7],["ACE_bloodIV",5],["ACE_bloodIV_500",4],["ACE_bloodIV_250",2],["BWA3_DM25",5,1],["BWA3_DM32_Red",2,1],["BWA3_DM32_Green",2,1]]],["BWA3_Kitbag_Fleck_Medic",[["ACE_elasticBandage",60],["ACE_packingBandage",70],["adv_aceCPR_AED",1],["ACE_quikclot",20],["BWA3_40Rnd_46x30_MP7",10,40]]],"BWA3_OpsCore_Fleck_Camera","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "rifle" : {[["BWA3_G38","","BWA3_acc_VarioRay_irlaser_black","BWA3_optic_ZO4x30i_MicroT2",["BWA3_30Rnd_556x45_G36_Tracer",30],[],"BWA3_bipod_Harris"],[],[],["BWA3_Uniform2_Fleck",[["ACE_tourniquet",4],["ACE_CableTie",5],["ACE_EntrenchingTool",1],["ACE_Flashlight_KSF1",1]]],["BWA3_Vest_Leader_Fleck",[["BWA3_DM25",5,1],["BWA3_DM32_Red",2,1],["BWA3_DM32_Green",2,1],["BWA3_30Rnd_556x45_G36_Tracer",12,30]]],["BWA3_Kitbag_Fleck",[["ACE_salineIV",2],["ACE_adenosine",5],["ACE_fieldDressing",30],["ACE_atropine",5],["BWA3_30Rnd_556x45_G36_Tracer",10,30]]],"BWA3_OpsCore_Fleck_Camera","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "pionier" : {[["BWA3_G38","","BWA3_acc_VarioRay_irlaser_black","BWA3_optic_ZO4x30i_MicroT2",["BWA3_30Rnd_556x45_G36_Tracer",30],[],"BWA3_bipod_Harris"],[],[],["BWA3_Uniform2_Fleck",[["ACE_EntrenchingTool",1],["ACE_Flashlight_KSF1",1],["ACE_tourniquet",4],["ACE_wirecutter",1]]],["BWA3_Vest_Leader_Fleck",[["ACE_CableTie",5],["ACE_DefusalKit",1],["BWA3_DM25",5,1],["BWA3_DM32_Red",2,1],["BWA3_DM32_Green",2,1],["DemoCharge_Remote_Mag",4,1]]],["BWA3_PatrolPack_Fleck",[["ACE_fieldDressing",30],["ACE_adenosine",5],["ACE_atropine",5],["ToolKit",1],["SatchelCharge_Remote_Mag",1,1],["BWA3_30Rnd_556x45_G36_Tracer",10,30]]],"BWA3_OpsCore_Fleck_Camera","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        default {[]};
        ss
        };

    ACE_player setUnitLoadout [_layout, true];
};

if (_arsenalType == "VANILLA") exitWith
{
    private _layout = switch (_rolle) do
    {
        case "lead": {[["arifle_MX_GL_Black_F","","ACE_acc_pointer_green","optic_ERCO_blk_F",["30Rnd_65x39_caseless_mag_Tracer",30],["ACE_HuntIR_M203",1],""],[],["hgun_Pistol_heavy_01_F","muzzle_snds_acp","","optic_MRD",["11Rnd_45ACP_Mag",11],[],""],["U_B_CTRG_1",[["ACE_fieldDressing",25],["ACE_atropine",9],["ACE_adenosine",2],["ACE_tourniquet",4]]],["V_PlateCarrier2_blk",[["ACE_MapTools",1],["ACE_Flashlight_KSF1",1],["ACE_EntrenchingTool",1],["ACE_CableTie",2],["ACE_HuntIR_monitor",1],["30Rnd_65x39_caseless_mag_Tracer",10,30],["Laserbatteries",1,1]]],["OPXT_blk_1523",[["1Rnd_Smoke_Grenade_shell",6,1],["1Rnd_SmokePurple_Grenade_shell",2,1],["ACE_HuntIR_M203",5,1]]],"H_HelmetSpecB","G_Bandanna_beast",["Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","ItemGPS","TFAR_anprc152_27","ItemCompass","ACE_Altimeter",""]]};
        case "grena": {[["arifle_MX_GL_Black_F","","ACE_acc_pointer_green","optic_ERCO_blk_F",["30Rnd_65x39_caseless_mag_Tracer",30],["1Rnd_Smoke_Grenade_shell",1],""],[],["hgun_Pistol_heavy_01_F","muzzle_snds_acp","","optic_MRD",["11Rnd_45ACP_Mag",11],[],""],["U_B_CTRG_1",[["ACE_fieldDressing",25],["ACE_adenosine",2],["ACE_atropine",9],["ACE_tourniquet",4]]],["V_PlateCarrier2_blk",[["ACE_CableTie",2],["ACE_MapTools",1],["ACE_Flashlight_KSF1",1],["ACE_EntrenchingTool",1],["ACE_HuntIR_monitor",1],["30Rnd_65x39_caseless_mag_Tracer",10,30]]],["B_Kitbag_rgr",[["ACE_salineIV",4],["3Rnd_Smoke_Grenade_shell",6,3],["3Rnd_HE_Grenade_shell",6,3]]],"H_HelmetSpecB","G_Bandanna_beast",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152_28","ItemCompass","ACE_Altimeter",""]]};
        case "arzt": {[[],[],["hgun_Pistol_heavy_01_F","muzzle_snds_acp","","optic_MRD",["11Rnd_45ACP_Mag",11],[],""],["U_B_CTRG_1",[["ACE_surgicalKit",1],["ACE_quikclot",25]]],["V_PlateCarrier2_blk",[["ACE_tourniquet",6],["ACE_elasticBandage",35],["ACE_packingBandage",50],["ACE_morphine",10],["ACE_atropine",15],["ACE_epinephrine",10],["ACE_adenosine",10],["ACE_MapTools",1],["ACE_Flashlight_KSF1",1],["ACE_CableTie",2]]],["B_Kitbag_sgg",[["ACE_bloodIV",10],["ACE_bloodIV_500",5],["adv_aceCPR_AED",1],["ACE_EntrenchingTool",1],["ACE_personalAidKit",1],["SmokeShellRed",8,1]]],"H_HelmetSpecB","G_Bandanna_beast",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "sani": {[["arifle_MX_Black_F","muzzle_snds_H","ACE_acc_pointer_green","optic_ERCO_blk_F",["30Rnd_65x39_caseless_mag_Tracer",30],[],"bipod_01_F_blk"],[],["hgun_Pistol_heavy_01_F","muzzle_snds_acp","","optic_MRD",["11Rnd_45ACP_Mag",11],[],""],["U_B_CTRG_1",[["ACE_surgicalKit",1],["ACE_quikclot",25]]],["V_PlateCarrier2_blk",[["ACE_elasticBandage",35],["ACE_packingBandage",50],["ACE_epinephrine",10],["ACE_morphine",10],["ACE_adenosine",10],["ACE_atropine",15],["ACE_tourniquet",6],["ACE_CableTie",4]]],["B_Kitbag_rgr",[["ACE_plasmaIV",10],["ACE_plasmaIV_500",5],["adv_aceCPR_AED",1],["30Rnd_65x39_caseless_mag_Tracer",10,30],["11Rnd_45ACP_Mag",3,11]]],"H_HelmetSpecB_sand","G_Bandanna_beast",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152_33","ItemCompass","ACE_Altimeter",""]]};
        case "mg": {[["LMG_03_F","","ACE_acc_pointer_green_IR","optic_ERCO_blk_F",["200Rnd_556x45_Box_F",200],[],""],[],["hgun_Pistol_heavy_01_F","muzzle_snds_acp","","optic_MRD",["11Rnd_45ACP_Mag",11],[],""],["U_B_CTRG_3",[["ACE_fieldDressing",25],["ACE_atropine",9],["ACE_adenosine",2],["ACE_tourniquet",4]]],["V_PlateCarrier2_blk",[["ACE_MapTools",1],["ACE_Flashlight_KSF1",1],["ACE_EntrenchingTool",1],["ACE_salineIV",4],["200Rnd_556x45_Box_Tracer_F",2,200]]],["B_Kitbag_rgr",[["200Rnd_556x45_Box_Tracer_F",3,200],["11Rnd_45ACP_Mag",2,11],["SmokeShell",4,1]]],"H_HelmetSpecB","G_Bandanna_beast",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152_30","ItemCompass","ACE_Altimeter",""]]};
        case "spreng": {[["arifle_MX_Black_F","","ACE_acc_pointer_green","optic_ERCO_blk_F",["30Rnd_65x39_caseless_mag",30],[],"bipod_01_F_blk"],[],["ACE_VMM3","","","",[],[],""],["U_B_CTRG_1",[["ACE_fieldDressing",25],["ACE_adenosine",2],["ACE_atropine",9],["ACE_tourniquet",4]]],["V_PlateCarrierGL_blk",[["ACE_Flashlight_KSF1",1],["ACE_M26_Clacker",1],["MineDetector",1],["ACE_wirecutter",1],["ACE_DefusalKit",1],["ACE_EntrenchingTool",1],["30Rnd_65x39_caseless_mag_Tracer",7,30]]],["B_Kitbag_rgr",[["DemoCharge_Remote_Mag",6,1]]],"H_HelmetSpecB_sand","G_Bandanna_beast",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152_31","ItemCompass","ACE_Altimeter",""]]} ;
        case "aaat": {[["arifle_MX_Black_F","","ACE_acc_pointer_green","optic_ERCO_blk_F",["30Rnd_65x39_caseless_mag_Tracer",30],[],"bipod_01_F_blk"],["launch_MRAWS_sand_F","","","",["MRAWS_HEAT_F",1],[],""],[],["U_B_CTRG_1",[["ACE_fieldDressing",25],["ACE_adenosine",2],["ACE_atropine",9],["ACE_tourniquet",4]]],["V_PlateCarrier2_blk",[["ACE_CableTie",2],["ACE_MapTools",1],["ACE_Flashlight_KSF1",1],["ACE_EntrenchingTool",1],["ACE_salineIV",4],["30Rnd_65x39_caseless_mag_Tracer",8,30]]],["B_Kitbag_rgr",[["MRAWS_HEAT_F",4,1],["SmokeShell",5,1]]],"H_HelmetSpecB","G_Bandanna_beast",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152_36","ItemCompass","ACE_Altimeter",""]]};
        case "trag": {[["arifle_MX_Black_F","","ACE_acc_pointer_green","optic_ERCO_blk_F",["30Rnd_65x39_caseless_mag_Tracer",30],[],"bipod_02_F_blk"],[],["hgun_Pistol_heavy_01_F","muzzle_snds_acp","","optic_MRD",["11Rnd_45ACP_Mag",11],[],""],["U_B_CTRG_1",[["ACE_fieldDressing",25],["ACE_adenosine",2],["ACE_atropine",9],["ACE_tourniquet",4]]],["V_PlateCarrier2_blk",[["ACE_salineIV",4],["30Rnd_65x39_caseless_mag_Tracer",10,30]]],["B_Carryall_cbr",[["MRAWS_HEAT_F",2,1],["20Rnd_762x51_Mag",5,20],["30Rnd_65x39_caseless_mag_Tracer",10,30],["200Rnd_556x45_Box_Tracer_Red_F",1,200]]],"H_HelmetSpecB_sand","G_Bandanna_beast",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152_37","ItemCompass","ACE_Altimeter",""]]} ;
        case "dmr": {[["srifle_EBR_F","","ACE_acc_pointer_green","optic_DMS",["20Rnd_762x51_Mag",20],[],"bipod_01_F_snd"],[],["hgun_Pistol_heavy_01_F","muzzle_snds_acp","","optic_MRD",["11Rnd_45ACP_Mag",11],[],""],["U_B_CTRG_1",[["ACE_fieldDressing",25],["ACE_adenosine",2],["ACE_atropine",9],["ACE_tourniquet",4]]],["V_PlateCarrier2_blk",[["ACE_CableTie",4],["ACE_MapTools",1],["ACE_Flashlight_KSF1",1],["ACE_EntrenchingTool",1],["ACE_salineIV",4],["20Rnd_762x51_Mag",7,20]]],["B_Kitbag_rgr",[["20Rnd_762x51_Mag",5,20],["11Rnd_45ACP_Mag",3,11],["SmokeShell",4,1]]],"H_HelmetSpecB_sand","G_Bandanna_beast",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152_35","ItemCompass","ACE_Altimeter",""]]};
        case "pilot": {[["SMG_01_F","","","optic_ACO_grn_smg",["30Rnd_45ACP_Mag_SMG_01",25],[],""],[],["hgun_Pistol_heavy_01_F","muzzle_snds_acp","","optic_MRD",["11Rnd_45ACP_Mag",11],[],""],["U_B_HeliPilotCoveralls",[["ACE_surgicalKit",1],["ACE_quikclot",25]]],["V_DeckCrew_white_F",[["adv_aceCPR_AED",1],["30Rnd_45ACP_Mag_SMG_01_Tracer_Yellow",2,25]]],["OPXT_wht_1523",[["ACE_plasmaIV",5],["ACE_elasticBandage",30],["ACE_packingBandage",35],["ACE_epinephrine",10],["ACE_adenosine",10],["ACE_morphine",10],["ACE_atropine",15]]],"H_CrewHelmetHeli_B","G_Bandanna_beast",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152_39","ItemCompass","ACE_Altimeter",""]]};
        case "sniper": {[["srifle_LRR_F","","","optic_LRPS",["7Rnd_408_Mag",7],[],""],[],["hgun_Pistol_heavy_01_F","muzzle_snds_acp","","optic_MRD",["11Rnd_45ACP_Mag",11],[],""],["U_B_FullGhillie_ard",[["ACE_fieldDressing",25],["ACE_tourniquet",4],["ACE_adenosine",3],["ACE_atropine",11],["ACE_EntrenchingTool",1],["ACE_ATragMX",1],["ACE_Kestrel4500",1],["ACE_Flashlight_KSF1",1],["ACE_MapTools",1],["ACE_RangeCard",1]]],["V_PlateCarrier2_blk",[["ACE_Tripod",1],["ACE_HuntIR_monitor",1],["7Rnd_408_Mag",5,7],["11Rnd_45ACP_Mag",1,11]]],["OPXT_blk_1523",[["ACE_wirecutter",1],["optic_KHS_blk",1],["optic_AMS",1],["7Rnd_408_Mag",6,7],["SmokeShellPurple",4,1],["Laserbatteries",1,1]]],"H_HelmetSpecB","G_Bandanna_beast",["ACE_Vector","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152_44","ItemCompass","ACE_Altimeter",""]]};
        case "spotter": {[["arifle_MX_GL_F","","","optic_ERCO_snd_F",["30Rnd_65x39_caseless_mag_Tracer",30],["ACE_HuntIR_M203",1],""],[],["hgun_Pistol_heavy_01_F","muzzle_snds_acp","","optic_MRD",["11Rnd_45ACP_Mag",11],[],""],["U_B_FullGhillie_ard",[["ACE_fieldDressing",25],["ACE_adenosine",2],["ACE_atropine",10],["ACE_EntrenchingTool",1],["ACE_Flashlight_KSF1",1],["ACE_tourniquet",4],["ACE_RangeCard",1],["ACE_ATragMX",1],["ACE_Kestrel4500",1],["ACE_MapTools",1],["ACE_CableTie",1]]],["V_PlateCarrier2_blk",[["ACE_SpottingScope",1],["ACE_HuntIR_monitor",1],["ACE_wirecutter",1],["30Rnd_65x39_caseless_mag_Tracer",5,30]]],["OPXT_blk_1523",[["ACE_salineIV",3],["3Rnd_Smoke_Grenade_shell",5,3],["3Rnd_HE_Grenade_shell",2,3],["ACE_HuntIR_M203",5,1],["Laserbatteries",1,1],["30Rnd_65x39_caseless_mag_Tracer",2,30]]],"H_HelmetSpecB_sand","G_Bandanna_beast",["Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","ItemGPS","TFAR_anprc152_45","ItemCompass","ACE_Altimeter",""]]};
        case "jtac": {[["arifle_MX_GL_Black_F","","","optic_ERCO_blk_F",["30Rnd_65x39_caseless_mag_Tracer",30],[],""],[],["hgun_Pistol_heavy_01_F","muzzle_snds_acp","","optic_MRD",["11Rnd_45ACP_Mag",11],[],""],["U_B_CTRG_1",[["ACE_fieldDressing",25],["ACE_adenosine",2],["ACE_atropine",9],["ACE_tourniquet",4]]],["V_PlateCarrier2_blk",[["ACE_MapTools",1],["ACE_Flashlight_KSF1",1],["ACE_UAVBattery",4],["ACE_HuntIR_monitor",1],["Laserbatteries",2,1],["30Rnd_65x39_caseless_mag_Tracer",2,30]]],["B_UAV_01_backpack_F",[]],"H_HelmetSpecB","G_Bandanna_beast",["Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","B_UavTerminal","TFAR_anprc152_4","ItemCompass","ACE_Altimeter",""]]};
        case "rifle" : {[["arifle_MX_F","","ACE_acc_pointer_green","optic_ERCO_snd_F",["30Rnd_65x39_caseless_mag_Tracer",30],[],"bipod_01_F_snd"],[],["hgun_Pistol_heavy_01_F","muzzle_snds_acp","","optic_MRD",["11Rnd_45ACP_Mag",11],[],""],["U_B_CTRG_1",[["ACE_fieldDressing",25],["ACE_adenosine",2],["ACE_tourniquet",4],["ACE_atropine",9]]],["V_PlateCarrier2_blk",[["ACE_MapTools",1],["ACE_Flashlight_KSF1",1],["ACE_EntrenchingTool",1],["ACE_wirecutter",1],["ACE_CableTie",2],["ACE_salineIV",4],["ACE_fieldDressing",20]]],["B_Kitbag_sgg",[["30Rnd_65x39_caseless_mag",10,30],["11Rnd_45ACP_Mag",5,11],["HandGrenade",5,1],["SmokeShell",5,1],["AMP_Breaching_Charge_Mag",5,1]]],"H_HelmetSpecB","G_Bandanna_oli",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152_5","ItemCompass","ACE_Altimeter",""]]};
        case "pionier" : {[["arifle_MX_F","","ACE_acc_pointer_green_IR","optic_ERCO_snd_F",["30Rnd_65x39_caseless_mag_Tracer",30],[],"bipod_01_F_snd"],[],["hgun_Pistol_heavy_01_F","muzzle_snds_acp","","optic_MRD",["11Rnd_45ACP_Mag",11],[],""],["U_B_CTRG_1",[["ACE_tourniquet",4],["ACE_atropine",9],["ACE_fieldDressing",25],["ACE_adenosine",2]]],["V_PlateCarrierGL_blk",[["ACE_wirecutter",1],["ACE_DefusalKit",1],["ACE_EntrenchingTool",1],["MineDetector",1],["ACE_CableTie",2],["ACE_MapTools",1],["ACE_Flashlight_KSF1",1],["SmokeShellBlue",2,1],["SmokeShellYellow",2,1],["SmokeShell",2,1],["30Rnd_65x39_caseless_mag_Tracer",5,30]]],["OPXT_blk_1523",[["ToolKit",1],["ACE_salineIV",4],["ACE_HuntIR_monitor",1]]],"H_HelmetSpecB","",[],["","","","","",""]]};
        default {[]};
    };

    ACE_player setUnitLoadout [_layout, true];
};

if (_arsenalType == "RUSS") exitWith
{
    ACE_player setUnitLoadout [[[],[],[],["rhs_uniform_emr_patchless",[["ACE_quikclot",15],["ACE_tourniquet",4],["ACE_Atropine",5],["ACE_MapTools",1],["ACE_CableTie",2],["ACE_EntrenchingTool",1]]],[],[],"rhs_fieldcap_digi","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ACE_Altimeter",""]], true];
};

if (_arsenalType == "Themen") exitWith
{
    private _patches = configfile >> "CfgPatches";
    private _side = side ACE_player;

    if (isClass (_patches >> "uns_main")) exitWith
    {
        ACE_player setUnitLoadout [[[],[],[],["UNS_ARMY_BDU_101stAB65pv1",[["ACE_quikclot",15],["ACE_tourniquet",2],["ACE_Atropine",3],["ACE_EntrenchingTool",1]]],["UNS_M1956_A12",[]],[],"UNS_M1_3A","",[],["ItemMap","","","ItemCompass","ItemWatch",""]], true];
    };

    if (_side == blufor) exitWith
    {
        if (worldName in ["gm_weferlingen_summer", "gm_weferlingen_winter"]) then
        {
            // BRD
            private _layout = switch (_rolle) do
            {
                case "lead": {[["gm_g3a3_grn","","","",["gm_20Rnd_762x51mm_B_T_DM21A1_g3_blk",20],[],""],[],["gm_p1_blk","","","",["gm_8Rnd_9x19mm_B_DM51_p1_blk",8],[],""],["gm_ge_army_uniform_soldier_parka_80_ols",[["ACE_fieldDressing",25],["ACE_tourniquet",4],["ACE_atropine",9],["ACE_adenosine",2]]],["gm_dk_army_vest_54_rifleman",[["ACE_MapTools",1],["ACE_CableTie",2],["ACE_Flashlight_KSF1",1],["ACE_EntrenchingTool",1],["AMP_Breaching_Charge_Mag",2,1]]],["OPXT_ogao_210",[["ACE_salineIV",2],["gm_smokeshell_wht_dm25",5,1],["gm_20Rnd_762x51mm_AP_DM151_g3_blk",5,20],["gm_20Rnd_762x51mm_B_T_DM21A1_g3_blk",5,20],["gm_8Rnd_9x19mm_B_DM11_p1_blk",5,8]]],"gm_ge_headgear_beret_crew_red_opcom","",["gm_df7x40_blk","","","",[],[],""],["ItemMap","","TFAR_anprc152","gm_ge_army_conat2","gm_watch_kosei_80",""]]};
                case "grena": {[["gm_g3a3_oli","","","",["gm_20Rnd_762x51mm_B_T_DM21A1_g3_blk",20],[],""],[],["gm_p1_blk","","","",["gm_8Rnd_9x19mm_B_DM11_p1_blk",8],[],""],["gm_ge_army_uniform_soldier_80_oli",[["ACE_fieldDressing",25],["ACE_tourniquet",4],["ACE_atropine",9],["ACE_adenosine",2]]],["gm_dk_army_vest_54_rifleman",[["ACE_MapTools",1],["ACE_CableTie",2],["ACE_Flashlight_KSF1",1],["ACE_EntrenchingTool",1],["ACE_wirecutter",1],["AMP_Breaching_Charge_Mag",2,1]]],["gm_ge_army_backpack_80_oli",[["ACE_salineIV",2],["gm_20Rnd_762x51mm_B_T_DM21A1_g3_blk",5,20],["gm_20Rnd_762x51mm_AP_DM151_g3_blk",5,20],["gm_8Rnd_9x19mm_B_DM11_p1_blk",5,8],["gm_1rnd_67mm_heat_dm22a1_g3",5,1],["gm_smokeshell_wht_dm25",4,1]]],"gm_dk_headgear_m52_net_oli","",["gm_df7x40_blk","","","",[],[],""],["ItemMap","","TFAR_anprc152","gm_ge_army_conat2","gm_watch_kosei_80",""]]};
                case "arzt": {[["gm_g3a3_oli","","","",["gm_20Rnd_762x51mm_B_T_DM21_g3_blk",20],[],""],[],[],["gm_ge_army_uniform_soldier_parka_80_oli",[["ACE_fieldDressing",25],["ACE_tourniquet",4],["ACE_atropine",9],["ACE_adenosine",2]]],["gm_ge_pol_vest_80_wht",[["ACE_elasticBandage",25],["ACE_packingBandage",50],["ACE_epinephrine",10],["ACE_adenosine",10],["ACE_morphine",10],["ACE_surgicalKit",1],["adv_aceCPR_AED",1]]],["gm_ge_backpack_satchel_80_san",[["ACE_atropine",10],["ACE_personalAidKit",1],["ACE_bloodIV",5],["ACE_bloodIV_500",7],["gm_20Rnd_762x51mm_AP_DM151_g3_blk",5,20]]],"gm_dk_headgear_m52_net_win","",["gm_df7x40_blk","","","",[],[],""],["ItemMap","","TFAR_anprc152","gm_ge_army_conat2","gm_watch_kosei_80",""]]};
                case "mg": {[["gm_mg3_blk","","","",["gm_120Rnd_762x51mm_B_T_DM21A1_mg3_grn",120],[],""],[],["gm_p1_blk","","","",["gm_8Rnd_9x19mm_B_DM11_p1_blk",8],[],""],["gm_ge_army_uniform_soldier_80_oli",[["ACE_fieldDressing",25],["ACE_tourniquet",4],["ACE_atropine",9],["ACE_adenosine",2]]],["gm_dk_army_vest_54_machinegunner",[["ACE_MapTools",1],["ACE_CableTie",2],["ACE_Flashlight_KSF1",1],["ACE_salineIV",2],["ACE_EntrenchingTool",1],["ACE_wirecutter",1]]],["gm_dk_army_backpack_73_oli",[["gm_120Rnd_762x51mm_B_T_DM21A1_mg3_grn",10,120],["gm_8Rnd_9x19mm_B_DM11_p1_blk",5,8],["gm_smokeshell_wht_dm25",5,1]]],"gm_dk_headgear_m52_net_oli","",["gm_df7x40_blk","","","",[],[],""],["ItemMap","","TFAR_anprc152","gm_ge_army_conat2","gm_watch_kosei_80",""]]};
                case "aaat": {[["gm_g3a3_grn","","","",["gm_20Rnd_762x51mm_B_T_DM21_g3_blk",20],[],""],["gm_pzf44_2_oli","","","",["gm_1Rnd_44x537mm_heat_dm32_pzf44_2",1],[],""],["gm_p1_blk","","","",["gm_8Rnd_9x19mm_B_DM11_p1_blk",8],[],""],["gm_ge_army_uniform_soldier_80_oli",[["ACE_fieldDressing",25],["ACE_tourniquet",4],["ACE_atropine",9],["ACE_adenosine",2]]],["gm_dk_army_vest_54_rifleman",[["ACE_MapTools",1],["ACE_CableTie",2],["ACE_Flashlight_KSF1",1],["ACE_EntrenchingTool",1],["ACE_wirecutter",1],["gm_smokeshell_wht_dm25",5,1],["gm_8Rnd_9x19mm_B_DM11_p1_blk",5,8]]],["gm_ge_army_backpack_80_oli",[["gm_1Rnd_44x537mm_heat_dm32_pzf44_2",3,1],["gm_20Rnd_762x51mm_AP_DM151_g3_blk",8,20]]],"gm_dk_headgear_m52_net_oli","",["gm_df7x40_blk","","","",[],[],""],["ItemMap","","TFAR_anprc152","gm_gc_compass_f73","gm_watch_kosei_80",""]]};
                case "trag": {[["gm_g3a3_oli","","","",["gm_20Rnd_762x51mm_B_T_DM21_g3_blk",20],[],""],[],["gm_p1_blk","","","",["gm_8Rnd_9x19mm_B_DM11_p1_blk",8],[],""],["gm_ge_army_uniform_soldier_80_oli",[["ACE_fieldDressing",25],["ACE_tourniquet",4],["ACE_atropine",9],["ACE_adenosine",2]]],["gm_dk_army_vest_54_rifleman",[["ACE_MapTools",1],["ACE_CableTie",2],["ACE_Flashlight_KSF1",1],["ACE_EntrenchingTool",1],["gm_20Rnd_762x51mm_B_T_DM21A1_g3_blk",10,20],["gm_8Rnd_9x19mm_B_DM51_p1_blk",2,8]]],["gm_dk_army_backpack_73_oli",[["gm_120Rnd_762x51mm_B_T_DM21A1_mg3_grn",2,120],["gm_1Rnd_44x537mm_heat_dm32_pzf44_2",1,1],["gm_20Rnd_762x51mm_B_T_DM21A1_g3_blk",12,20],["gm_8Rnd_9x19mm_B_DM11_p1_blk",5,8]]],"gm_dk_headgear_m52_net_oli","",["gm_df7x40_blk","","","",[],[],""],["ItemMap","","TFAR_anprc152","gm_ge_army_conat2","gm_watch_kosei_80",""]]};
                case "pionier" : {[["gm_g3a3_oli","","","",["gm_20Rnd_762x51mm_B_T_DM21_g3_blk",20],[],""],[],["ACE_VMM3","","","",[],[],""],["gm_ge_army_uniform_soldier_80_ols",[["ACE_fieldDressing",25],["ACE_tourniquet",4],["ACE_atropine",9],["ACE_adenosine",2]]],["gm_dk_army_vest_54_rifleman",[["ACE_MapTools",1],["ACE_CableTie",2],["ACE_Flashlight_KSF1",1],["gm_20Rnd_762x51mm_AP_DM151_g3_blk",5,20],["gm_20Rnd_762x51mm_B_T_DM21_g3_blk",5,20]]],["gm_ge_army_backpack_80_oli",[["gm_repairkit_01",1],["ACE_M26_Clacker",1],["ACE_wirecutter",1],["ACE_DefusalKit",1],["gm_explosive_petn_charge",4,1],["AMP_Breaching_Charge_Mag",2,1]]],"gm_ge_bgs_headgear_m35_53_net_blk","",["gm_df7x40_blk","","","",[],[],""],["ItemMap","","TFAR_anprc152","gm_ge_army_conat2","gm_watch_kosei_80",""]]};
                default {[]};
            };

            ACE_player setUnitLoadout [_layout, true];
        }
        else
        {
            // Vanilla-COP
            //ACE_player setUnitLoadout [[[],[],["TB_weap_taser","","acc_flashlight_pistol","optic_MRD",["TB_mag_taser",3],[],""],["TB_Uniform_Kommissar_U",[["ACE_quikclot",25],["ACE_Atropine",5],["ACE_tourniquet",4],["ACE_CableTie",5]]],["V_TacVest_blk_POLICE",[["AMP_Breaching_Charge_Mag",1,1],["TB_mag_taser",1,3]]],[],"H_Cap_police","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]], true];

            // WoMi Polizei
            private _layout = switch (_rolle) do
            {
                case "lead";
                case "sani": {[[],[],["rhsusf_weap_glock17g4","","acc_flashlight_pistol","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["TB_Uniform_Sek_U",[["ACE_tourniquet",4],["ACE_fieldDressing",10],["ACE_adenosine",2],["ACE_epinephrine",2]]],["V_TacVest_blk_POLICE",[["ACE_CableTie",6],["rhsusf_mag_17Rnd_9x19_JHP",4,17],["ACE_M84",1,1]]],[],"H_Cap_police","",[],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""]]};
                case "arzt";
                case "rifle": {[["rhs_weap_mk18","","","rhsusf_acc_su230",["rhs_mag_30Rnd_556x45_M855_Stanag",30],[],""],[],["TB_weap_taser","","acc_flashlight_pistol","optic_MRD",["TB_mag_taser",3],[],""],["rhs_uniform_g3_blk",[["ACE_atropine",6],["ACE_adenosine",2],["ACE_CableTie",6],["TB_mag_taser",1,3]]],["TB_vest_SWAT",[["TB_mag_taser",1,3],["rhs_mag_30Rnd_556x45_M855_Stanag",6,30],["ACE_M84",2,1],["SmokeShell",1,1],["AMP_Breaching_Charge_Mag",1,1]]],[],"TB_helmet_SWAT_01","",[],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""]]};
                default {[]};
            };

            ACE_player setUnitLoadout [_layout, true];
        };
    };

    if (_side == opfor) exitWith
    {
        // RussSimple
        ACE_player setUnitLoadout [[[],[],[],["rhs_uniform_flora_patchless",[["ACE_fieldDressing",10],["ACE_quikclot",10],["ACE_tourniquet",4],["ACE_Atropine",5],["ACE_MapTools",1],["ACE_CableTie",1]]],[],[],"rhs_beret_milp","",[],["ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ACE_Altimeter",""]], true];
    };

    if (_side == independent) exitWith
    {
        // LDF
        ACE_player setUnitLoadout [[[],[],[],["U_I_E_Uniform_01_F",[]],["V_CarrierRigKBT_01_light_Olive_F",[]],[],"H_HelmetHBK_headset_F","",["Binocular","","","",[],[],""],["ItemMap","I_E_UavTerminal","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]], true];
    };
};

if (_arsenalType == "CUSTOM") exitWith
{
    if (isNil "TB_fnc_customLayout") then
    {
        TB_fnc_customLayout = {//Not changed for backward comp.
            params ["_rolle"];

            switch (_rolle) do
            {
                case "lead": {[]};
                case "grena": {[]};
                case "sani": {[]};
                case "mg": {[]};
                case "spreng": {[]};
                case "aaat": {[]};
                case "trag": {[]};
                case "dmr": {[]};
                case "pilot": {[]};
                case "sniper": {[]};
                case "spotter": {[]};
                case "jtac": {[]};
                case "arzt": {[]};
                case "rifle" : {[]};
                case "pionier" : {[]};
                default {[]};
            };
        };
    };

    private _layout = [_rolle] call TB_fnc_customLayout;

    ACE_player setUnitLoadout [_layout, true];
};
