#include "../script_component.hpp"
/*
    Part of the TBMod ( https://github.com/TacticalBaconDevs/TBMod )
    Developed by http://tacticalbacon.de
*/
private _arsenalType = ACE_player getVariable ["TB_arsenalType", ""];
private _rolle = ACE_player getVariable ["TB_rolle", ""];

if (_arsenalType == "USA") exitWith
{
    private _layout = switch (_rolle) do
    {
        case "lead": {[["rhs_weap_m4a1_blockII_bk","","rhsusf_acc_anpeq15side_bk","rhsusf_acc_ACOG_RMR",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],"rhsusf_acc_harris_bipod"],[],["rhs_weap_M320","","","",["3Rnd_Smoke_Grenade_shell_precise",3],[],""],["rhs_uniform_acu_ucp",[["ACE_tourniquet",4],["ACE_Flashlight_KSF1",1],["ACE_HuntIR_monitor",1]]],["rhsusf_iotv_ucp_Teamleader",[["3Rnd_Smoke_Grenade_shell_precise",1,3],["ACE_HuntIR_M203",3,1],["TB_rhs_mag_40mm_HE",3,1],["TB_rhs_mag_40mm_HEDP",3,1],["rhs_mag_mk3a2",2,1],["SmokeShellBlue",2,1],["SmokeShellRed",2,1],["SmokeShell",3,1]]],["OPXT_ogag_1523",[["ACE_packingBandage",20],["ACE_quikclot",5],["ACE_morphine",5],["ACE_salineIV_500",1],["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",12,30]]],"rhsusf_opscore_mar_ut_pelt","",["ACE_Vector","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "grena": {[["rhs_weap_m4a1_blockII_M203","","rhsusf_acc_anpeq15side_bk","rhsusf_acc_ACOG_RMR",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],["3Rnd_Smoke_Grenade_shell_precise",3],""],[],[],["rhs_uniform_acu_ucp",[["ACE_HuntIR_monitor",1],["ACE_tourniquet",4],["ACE_Flashlight_KSF1",1]]],["rhsusf_iotv_ucp_Grenadier",[["3Rnd_Smoke_Grenade_shell_precise",1,3],["ACE_HuntIR_M203",2,1],["rhs_mag_m713_Red_precise",1,1],["TB_rhs_mag_40mm_HE",6,1],["TB_rhs_mag_40mm_HEDP",4,1],["SmokeShellBlue",1,1],["rhs_mag_mk3a2",1,1],["SmokeShell",3,1]]],["rhsusf_assault_eagleaiii_ucp",[["ACE_packingBandage",20],["ACE_quikclot",5],["ACE_morphine",5],["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",12,30]]],"rhsusf_opscore_mar_ut_pelt","",["m24_bino","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "sani": {[["rhs_weap_m4a1_blockII_bk","","rhsusf_acc_anpeq15side_bk","rhsusf_acc_g33_xps3",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],"rhsusf_acc_harris_bipod"],[],[],["rhs_uniform_acu_ucp",[["adv_aceCPR_AED",1],["ACE_tourniquet",4],["ACE_Flashlight_KSF1",1]]],["rhsusf_iotv_ucp_Medic",[["ACE_tourniquet",10],["ACE_plasmaIV",4],["ACE_surgicalKit",1],["TB_med_thrombin",2],["ACE_quikclot",10],["ACE_morphine",20],["SmokeShell",3,1],["SmokeShellBlue",1,1]]],["rhsusf_assault_eagleaiii_ucp",[["ACE_elasticBandage",40],["ACE_quikclot",40],["ACE_epinephrine",5],["ACE_plasmaIV_500",4],["rhs_mag_mk3a2",1,1],["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",9,30]]],"TB_helmet_Sani_B_Grey","",["m24_bino","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "mg": {[["rhs_weap_m249_light_S","","","rhsusf_acc_eotech_552",["rhsusf_200Rnd_556x45_M855_mixed_soft_pouch_ucp",200],[],"rhsusf_acc_saw_lw_bipod"],[],[],["rhs_uniform_acu_ucp",[["ACE_tourniquet",4],["ACE_RangeCard",1],["ACE_Flashlight_KSF1",1]]],["rhsusf_iotv_ucp_SAW",[["rhs_mag_mk3a2",1,1],["SmokeShellBlue",1,1],["SmokeShell",3,1]]],["rhsusf_assault_eagleaiii_ucp",[["ACE_packingBandage",20],["ACE_quikclot",5],["ACE_morphine",5],["rhsusf_200Rnd_556x45_M855_mixed_soft_pouch_ucp",4,200]]],"rhsusf_opscore_mar_ut_pelt","",["m24_bino","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "spreng": {[["rhs_weap_m4a1_blockII_bk","","rhsusf_acc_anpeq15side_bk","rhsusf_acc_ACOG_RMR",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],"rhsusf_acc_harris_bipod"],[],[],["rhs_uniform_acu_ucp",[["ACE_wirecutter",1],["ACE_tourniquet",4],["ACE_M26_Clacker",1],["ACE_Flashlight_KSF1",1]]],["rhsusf_iotv_ucp_Rifleman",[["ACE_DefusalKit",1],["ToolKit",1],["rhs_mag_mk3a2",1,1],["SmokeShellBlue",1,1],["SmokeShell",3,1],["DemoCharge_Remote_Mag",2,1]]],["rhsusf_assault_eagleaiii_ucp",[["ACE_packingBandage",20],["ACE_quikclot",5],["ACE_morphine",5],["AMP_Breaching_Charge_Mag",2,1],["SLAMDirectionalMine_Wire_Mag",2,1],["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",9,30]]],"rhsusf_opscore_ut_pelt","",["Binocular","","","",[],[],""],["ItemMap","B_UavTerminal","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "aaat": {[["rhs_weap_m4a1_blockII_KAC_bk","","rhsusf_acc_anpeq15side_bk","rhsusf_acc_ACOG_RMR",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],"rhsusf_acc_harris_bipod"],["rhs_weap_maaws","","","rhs_optic_maaws",["rhs_mag_maaws_HEAT",1],[],""],[],["rhs_uniform_acu_ucp",[["ACE_Flashlight_KSF1",1],["ACE_tourniquet",4]]],["rhsusf_spcs_ucp_saw",[["rhs_mag_mk3a2",1,1],["SmokeShellBlue",1,1],["SmokeShell",3,1],["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",9,30]]],["B_Carryall_cbr",[["ACE_packingBandage",20],["ACE_quikclot",5],["ACE_morphine",5],["rhs_mag_maaws_HEAT",2,1]]],"rhsusf_opscore_mar_ut_pelt","",["Leupold_Mk4","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "trag": {[["rhs_weap_m4a1_blockII_bk","","rhsusf_acc_anpeq15side_bk","rhsusf_acc_ACOG_RMR",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],"rhsusf_acc_harris_bipod"],[],[],["rhs_uniform_acu_ucp",[["ACE_Flashlight_KSF1",1],["ACE_tourniquet",4]]],["rhsusf_spcs_ucp_machinegunner",[["rhs_mag_mk3a2",1,1],["SmokeShell",3,1],["SmokeShellBlue",1,1]]],["TB_backpacks_bergen_urban",[["ACE_packingBandage",20],["ACE_quikclot",5],["ACE_morphine",5],["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",20,30]]],"rhsusf_opscore_mar_ut_pelt","",["ACE_Vector","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter","rhsusf_ANPVS_15"]]};
        case "pilot": {[["rhsusf_weap_MP7A2","","","",["rhsusf_mag_40Rnd_46x30_FMJ",40],[],""],[],[],["rhs_uniform_cu_ucp",[["ACE_tourniquet",4],["adv_aceCPR_AED",1],["ACE_Flashlight_KSF1",1]]],["rhsusf_iotv_ucp",[["ACE_surgicalKit",1],["ACE_packingBandage",5]]],["OPXT_ogag_1523",[["ACE_plasmaIV_500",1],["ACE_quikclot",10],["ACE_epinephrine",2],["ACE_morphine",5],["ToolKit",1],["SmokeShell",3,1],["SmokeShellBlue",2,1],["SmokeShellRed",2,1],["rhs_mag_mk3a2",1,1],["rhsusf_mag_40Rnd_46x30_FMJ",2,40]]],"rhsusf_hgu56p_black","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "sniper": {[["rhs_weap_m24sws","rhsusf_acc_m24_silencer_black","","rhsusf_acc_premier",["rhsusf_5Rnd_762x51_m118_special_Mag",3],[],""],[],[],["rhs_uniform_cu_ucp",[["ACE_tourniquet",4],["ACE_ATragMX",1],["ACE_RangeCard",1],["ACE_Kestrel4500",1]]],["rhsusf_iotv_ucp_Rifleman",[["ACE_Tripod",1],["rhs_mag_mk3a2",1,1],["SmokeShell",3,1],["SmokeShellBlue",2,1],["SmokeShellRed",2,1]]],["rhsusf_assault_eagleaiii_ucp",[["ACE_packingBandage",10],["ACE_quikclot",30],["ACE_morphine",5],["ACE_salineIV_500",1],["rhsusf_5Rnd_762x51_m118_special_Mag",12,5]]],"rhsusf_opscore_mar_ut_pelt","",["ACE_Vector","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "spotter": {[["rhs_weap_m4a1_blockII_M203","rhsusf_acc_nt4_black","rhsusf_acc_anpeq15side_bk","rhsusf_acc_ACOG_RMR",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],["TB_rhs_mag_40mm_IR_Grenade",1],""],[],[],["rhs_uniform_cu_ucp",[["ACE_tourniquet",4],["ACE_Kestrel4500",1],["ACE_RangeCard",1],["ACE_DefusalKit",1],["ACE_HuntIR_monitor",1],["ACE_ATragMX",1]]],["rhsusf_iotv_ucp_Grenadier",[["rhs_mag_mk3a2",1,1],["SmokeShell",3,1],["SmokeShellRed",2,1],["SmokeShellBlue",2,1],["ACE_HuntIR_M203",2,1],["3Rnd_Smoke_Grenade_shell_precise",1,3],["rhs_mag_m713_Red_precise",1,1],["TB_rhs_mag_40mm_HE",3,1]]],["OPXT_ogag_1523",[["ACE_packingBandage",10],["ACE_quikclot",30],["ACE_salineIV_500",1],["ACE_morphine",5],["rhs_mag_30Rnd_556x45_M855A1_PMAG",10,30]]],"rhsusf_opscore_mar_ut_pelt","",["Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "jtac": {[["rhs_weap_mk18_KAC","","","rhsusf_acc_ACOG_RMR",["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",30],[],"rhsusf_acc_harris_bipod"],[],[],["rhs_uniform_acu_ucp",[["ACE_tourniquet",4],["ACE_Flashlight_KSF1",1]]],["rhsusf_spcs_ucp_rifleman",[["ACE_packingBandage",20],["ACE_quikclot",5],["ACE_morphine",5],["rhs_mag_mk3a2",1,1],["SmokeShell",3,1],["SmokeShellBlue",1,1],["SmokeShellRed",1,1],["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_Red",8,30]]],["OPXT_ogag_1523",[]],"rhsusf_opscore_mar_ut_pelt","",["Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","B_UavTerminal","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "arzt": {[["rhsusf_weap_MP7A2","","","",["rhsusf_mag_40Rnd_46x30_FMJ",40],[],"rhsusf_acc_grip2"],[],[],["rhs_uniform_acu_ucp",[["ACE_tourniquet",4],["adv_aceCPR_AED",1]]],["rhsusf_iotv_ucp_Medic",[["ACE_surgicalKit",1],["SmokeShell",3,1],["SmokeShellBlue",1,1],["SmokeShellRed",1,1],["rhs_mag_mk3a2",1,1]]],["B_Kitbag_cbr",[["ACE_elasticBandage",60],["ACE_packingBandage",60],["ACE_quikclot",20],["ACE_bloodIV_500",2],["ACE_bloodIV",1],["ACE_bloodIV_250",4],["ACE_epinephrine",5],["ACE_morphine",15],["ACE_tourniquet",15],["TB_med_thrombin",5],["rhsusf_mag_40Rnd_46x30_FMJ",5,40]]],"TB_helmet_Sani_B_Grey","",["m24_bino","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "rifle" : {[["rhs_weap_sr25","","","optic_SOS",["rhsusf_20Rnd_762x51_SR25_m62_Mag",20],[],"rhsusf_acc_harris_bipod"],[],[],["rhs_uniform_acu_ucp",[["ACE_tourniquet",4],["ACE_Flashlight_KSF1",1],["ACE_Kestrel4500",1],["ACE_RangeCard",1]]],["rhsusf_spcs_ucp_rifleman",[["rhs_mag_mk3a2",1,1],["SmokeShell",3,1],["SmokeShellRed",1,1],["SmokeShellBlue",1,1],["rhsusf_20Rnd_762x51_SR25_m62_Mag",4,20]]],["rhsusf_assault_eagleaiii_ucp",[["ACE_packingBandage",20],["ACE_quikclot",5],["ACE_morphine",5],["rhs_mag_20Rnd_SCAR_762x51_m118_special",9,20],["rhsusf_20Rnd_762x51_SR25_m62_Mag",5,20]]],"rhsusf_opscore_mar_ut_pelt","",["ACE_Vector","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "pionier" : {[["rhs_weap_m4a1_blockII_KAC_bk","","rhsusf_acc_anpeq15side_bk","rhsusf_acc_ACOG_RMR",["rhs_mag_30Rnd_556x45_M855A1_PMAG",30],[],"rhsusf_acc_harris_bipod"],[],["ACE_VMM3","","","",[],[],""],["rhs_uniform_acu_ucp",[["ACE_tourniquet",4],["ACE_Flashlight_KSF1",1],["ACE_DefusalKit",1],["ACE_wirecutter",1]]],["rhsusf_spcs_ucp_rifleman",[["ToolKit",1],["rhs_mag_mk3a2",1,1],["SmokeShell",3,1],["SmokeShellBlue",1,1],["SmokeShellRed",1,1]]],["rhsusf_assault_eagleaiii_ucp",[["ACE_packingBandage",20],["ACE_quikclot",5],["ACE_morphine",5],["rhs_mag_30Rnd_556x45_M855A1_PMAG",10,30]]],"rhsusf_opscore_mar_ut_pelt","",["m24_bino","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        default {[]};
    };

    ACE_player setUnitLoadout [_layout, true];
};

if (_arsenalType == "UK") exitWith
{
    private _layout = switch (_rolle) do
    {
        case "lead": {[["UK3CB_BAF_L85A2_RIS","","","RKSL_optic_RMR_RM33",["UK3CB_BAF_556_30Rnd",30],[],""],[],["rhs_weap_M320","","","",["ACE_HuntIR_M203",1],[],""],["UK3CB_BAF_U_CombatUniform_DDPM_ShortSleeve",[["ACE_MapTools",1],["ACE_HuntIR_monitor",1],["ACE_Flashlight_KSF1",1],["ACE_CableTie",5],["ACE_microDAGR",1],["ACE_salineIV_250",1],["ACE_morphine",10]]],["UK3CB_BAF_V_Osprey_DDPM8",[["ACE_packingBandage",30],["SmokeShell",5,1],["SmokeShellBlue",2,1],["SmokeShellGreen",2,1],["SmokeShellRed",2,1],["TB_rhs_mag_40mm_HE",4,1],["ACE_HuntIR_M203",4,1],["3Rnd_Smoke_Grenade_shell_precise",1,3]]],["UK3CB_BAF_B_Bergen_DDPM_JTAC_H_A",[["ACE_tourniquet",4],["UK3CB_BAF_556_30Rnd_T",9,30]]],"UK3CB_BAF_H_Mk6_DDPM_A","",["Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "grena": {[["UK3CB_BAF_L85A2_UGL_HWS","","UK3CB_BAF_LLM_Flashlight_Black","RKSL_optic_EOT552",["UK3CB_BAF_556_30Rnd_T",30],["3Rnd_Smoke_Grenade_shell_precise",3],""],[],["UK3CB_BAF_L9A1","","","",["30Rnd_9x21_Green_Mag",30],[],""],["UK3CB_BAF_U_CombatUniform_DDPM_ShortSleeve",[["ACE_MapTools",1],["ACE_HuntIR_monitor",1],["ACE_Flashlight_KSF1",1],["ACE_CableTie",5],["ACE_salineIV_250",1],["ACE_morphine",10]]],["UK3CB_BAF_V_Osprey_DDPM3",[["ACE_packingBandage",30],["3Rnd_Smoke_Grenade_shell_precise",2,3],["TB_rhs_mag_40mm_HE",11,1],["ACE_HuntIR_M203",2,1]]],["UK3CB_BAF_B_Kitbag_TAN",[["ACE_tourniquet",4],["UK3CB_BAF_556_30Rnd_T",10,30],["TB_rhs_mag_40mm_Slugshot",5,1],["TB_rhs_mag_40mm_HEDP",5,1]]],"UK3CB_BAF_H_Mk6_DDPM_A","",["m24_bino","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "arzt": {[[],[],[],["UK3CB_BAF_U_CombatUniform_DDPM_ShortSleeve",[["ACE_MapTools",1],["ACE_Flashlight_KSF1",1],["ACE_CableTie",5],["ACE_salineIV_250",1],["ACE_morphine",10]]],[],[],"UK3CB_BAF_H_Mk6_DDPM_A","",[],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "sani": {[["UK3CB_BAF_L85A2_RIS_Tan","","UK3CB_BAF_LLM_Flashlight_Black","RKSL_optic_EOT552",["UK3CB_BAF_556_30Rnd_T",30],[],""],[],[],["UK3CB_BAF_U_CombatUniform_DDPM_ShortSleeve",[["ACE_surgicalKit",1],["ACE_CableTie",5],["ACE_MapTools",1],["ACE_Flashlight_KSF1",1],["ACE_morphine",10],["ACE_epinephrine",6],["ACE_morphine",6]]],["UK3CB_BAF_V_Osprey_DDPM1",[["ACE_quikclot",30],["ACE_packingBandage",40],["ACE_elasticBandage",50],["ACE_EntrenchingTool",1]]],["UK3CB_BAF_B_Kitbag_TAN",[["adv_aceCPR_AED",1],["ACE_plasmaIV",10],["ACE_plasmaIV_500",10],["ACE_plasmaIV_250",5],["UK3CB_BAF_556_30Rnd_T",8,30]]],"UK3CB_BAF_H_Mk6_DDPM_A","",["m24_bino","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "mg": {[["UK3CB_BAF_L110A3","","","",["UK3CB_BAF_556_200Rnd",200],[],""],[],["UK3CB_BAF_L9A1","","","",["UK3CB_BAF_9_13Rnd",13],[],""],["UK3CB_BAF_U_CombatUniform_DDPM_ShortSleeve",[["ACE_MapTools",1],["ACE_Flashlight_KSF1",1],["ACE_CableTie",5],["ACE_salineIV_250",1],["ACE_morphine",10],["ACE_RangeCard",1],["ACE_EntrenchingTool",1]]],["UK3CB_BAF_V_Osprey_DDPM8",[["ACE_packingBandage",30],["SmokeShell",5,1]]],["UK3CB_BAF_B_Kitbag_DDPM",[["ACE_tourniquet",4],["UK3CB_BAF_556_200Rnd_T",3,200],["30Rnd_9x21_Green_Mag",2,30]]],"UK3CB_BAF_H_Mk6_DDPM_A","",["m24_bino","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "spreng": {[["UK3CB_BAF_L85A2_RIS_Tan","","UK3CB_BAF_LLM_Flashlight_Black","RKSL_optic_RMR_RM33",["UK3CB_BAF_556_30Rnd",30],[],""],[],["ACE_VMM3","","","",[],[],""],["UK3CB_BAF_U_CombatUniform_DDPM_ShortSleeve",[["ACE_MapTools",1],["ACE_Flashlight_KSF1",1],["ACE_CableTie",5],["ACE_salineIV_250",1],["ACE_morphine",10],["ACE_EntrenchingTool",1],["ACE_M26_Clacker",1],["ACE_DeadManSwitch",1],["ACE_DefusalKit",1]]],["UK3CB_BAF_V_Osprey_DDPM5",[["ACE_packingBandage",30],["DemoCharge_Remote_Mag",4,1]]],["UK3CB_BAF_B_Kitbag_TAN",[["ToolKit",1],["ACE_wirecutter",1],["SmokeShell",5,1],["SatchelCharge_Remote_Mag",1,1],["UK3CB_BAF_556_30Rnd_T",7,30]]],"UK3CB_BAF_H_Mk6_DDPM_A","",[],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "aaat": {[["UK3CB_BAF_L85A2_RIS_Tan","","UK3CB_BAF_LLM_Flashlight_Black","RKSL_optic_RMR_RM33",["UK3CB_BAF_556_30Rnd_T",30],[],""],["rhs_weap_maaws","","","",["rhs_mag_maaws_HEAT",1],[],""],["UK3CB_BAF_L9A1","","","",["UK3CB_BAF_9_13Rnd",13],[],""],["UK3CB_BAF_U_CombatUniform_DDPM_ShortSleeve",[["ACE_MapTools",1],["ACE_Flashlight_KSF1",1],["ACE_CableTie",5],["ACE_salineIV_250",1],["ACE_morphine",10],["ACE_EntrenchingTool",1]]],["UK3CB_BAF_V_Osprey_DDPM2",[["ACE_packingBandage",30],["UK3CB_BAF_556_30Rnd_T",7,30]]],["UK3CB_BAF_B_Carryall_DDPM",[["rhs_mag_maaws_HEAT",2,1],["rhs_mag_maaws_HE",1,1],["SmokeShell",5,1]]],"UK3CB_BAF_H_Mk6_DDPM_A","",[],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "trag": {[["UK3CB_BAF_L85A2_RIS_Tan","","","RKSL_optic_RMR_RM33",["UK3CB_BAF_556_30Rnd",30],[],""],[],[],["UK3CB_BAF_U_CombatUniform_DDPM_ShortSleeve",[["ACE_MapTools",1],["ACE_Flashlight_KSF1",1],["ACE_CableTie",5],["ACE_salineIV_250",1],["ACE_morphine",10],["ACE_EntrenchingTool",1]]],["UK3CB_BAF_V_Osprey_DDPM5",[["ACE_packingBandage",30],["SmokeShell",5,1],["UK3CB_BAF_556_30Rnd_T",8,30]]],["UK3CB_BAF_B_Carryall_DDPM",[["ACE_tourniquet",4],["UK3CB_BAF_556_200Rnd_T",2,200],["UK3CB_BAF_556_30Rnd_T",17,30]]],"UK3CB_BAF_H_Mk6_DDPM_A","",["ACE_Vector","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "dmr": {[]};
        case "pilot": {[["UK3CB_BAF_L91A1","","","",["UK3CB_BAF_9_30Rnd",30],[],""],[],[],["UK3CB_BAF_U_CombatUniform_DDPM_ShortSleeve",[["ACE_MapTools",1],["ACE_Flashlight_KSF1",1],["ACE_CableTie",5],["ACE_salineIV_250",1],["ACE_morphine",10],["ACE_surgicalKit",1],["ACE_tourniquet",7]]],["UK3CB_BAF_V_Osprey_DDPM1",[["ACE_quikclot",30],["ACE_elasticBandage",40],["ACE_packingBandage",40],["adv_aceCPR_AED",1]]],["UK3CB_BAF_B_Bergen_DDPM_JTAC_H_A",[["ACE_epinephrine",8],["ACE_morphine",8],["ACE_morphine",10],["ToolKit",1],["ACE_bodyBag",2],["UK3CB_BAF_9_30Rnd",7,30]]],"H_PilotHelmetFighter_B","",["m24_bino","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "sniper": {[[],[],[],["UK3CB_BAF_U_CombatUniform_DDPM_ShortSleeve",[["ACE_MapTools",1],["ACE_Flashlight_KSF1",1],["ACE_CableTie",5],["ACE_salineIV_250",1],["ACE_morphine",10]]],[],[],"UK3CB_BAF_H_Mk6_DDPM_A","",[],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "spotter": {[[],[],[],["UK3CB_BAF_U_CombatUniform_DDPM_ShortSleeve",[["ACE_MapTools",1],["ACE_Flashlight_KSF1",1],["ACE_CableTie",5],["ACE_salineIV_250",1],["ACE_morphine",10]]],[],[],"UK3CB_BAF_H_Mk6_DDPM_A","",[],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "jtac": {[[],[],[],["UK3CB_BAF_U_CombatUniform_DDPM_ShortSleeve",[["ACE_MapTools",1],["ACE_Flashlight_KSF1",1],["ACE_CableTie",5],["ACE_salineIV_250",1],["ACE_morphine",10]]],[],[],"UK3CB_BAF_H_Mk6_DDPM_A","",[],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "rifle" : {[["rhs_weap_mk17_CQC","","UK3CB_BAF_LLM_Flashlight_Black","RKSL_optic_LDS_PiP",["rhs_mag_20Rnd_SCAR_762x51_m62_tracer",20],[],""],[],[],["UK3CB_BAF_U_CombatUniform_DDPM_ShortSleeve",[["ACE_MapTools",1],["ACE_Flashlight_KSF1",1],["ACE_CableTie",5],["ACE_salineIV_250",1],["ACE_morphine",10],["ACE_EntrenchingTool",1]]],["UK3CB_BAF_V_Osprey_DDPM5",[["ACE_packingBandage",30],["AMP_Breaching_Charge_Mag",5,1]]],["UK3CB_BAF_B_Kitbag_TAN",[["ACE_tourniquet",4],["rhs_mag_20Rnd_SCAR_762x51_m62_tracer",9,20],["SmokeShell",6,1]]],"UK3CB_BAF_H_Mk6_DDPM_A","",["m24_bino","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "pionier" : {[["UK3CB_BAF_L85A2_RIS_Tan","","UK3CB_BAF_LLM_Flashlight_Black","RKSL_optic_RMR_RM33",["UK3CB_BAF_556_30Rnd",30],[],""],[],["ACE_VMM3","","","",[],[],""],["UK3CB_BAF_U_CombatUniform_DDPM_ShortSleeve",[["ACE_MapTools",1],["ACE_Flashlight_KSF1",1],["ACE_CableTie",5],["ACE_salineIV_250",1],["ACE_morphine",10],["ACE_EntrenchingTool",1],["ACE_DefusalKit",1]]],["UK3CB_BAF_V_Osprey_DDPM5",[["ACE_packingBandage",30],["UK3CB_BAF_556_30Rnd_T",6,30]]],["UK3CB_BAF_B_Bergen_DDPM_JTAC_H_A",[["ToolKit",1],["ACE_tourniquet",5],["ACE_wirecutter",1],["SmokeShell",5,1],["UK3CB_BAF_556_30Rnd_T",7,30]]],"UK3CB_BAF_H_Mk6_DDPM_A","",["m24_bino","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        default {[]};
    };

    ACE_player setUnitLoadout [_layout, true];
};

if (_arsenalType == "BW") exitWith
{
    private _layout = switch (_rolle) do
    {
        case "lead": {[["BWA3_G36A3","","","BWA3_optic_ZO4x30i_MicroT2",["BWA3_30Rnd_556x45_G36",30],[],"BWA3_bipod_Atlas"],[],["rhs_weap_M320","","","",["3Rnd_Smoke_Grenade_shell_precise",3],[],""],["BWA3_Uniform_Multi",[["ACE_Flashlight_KSF1",1],["ACE_HuntIR_monitor",1],["BWA3_optic_NSV600",1],["ACE_tourniquet",4],["ACE_MapTools",1]]],["BWA3_Vest_Leader_Multi",[["3Rnd_Smoke_Grenade_shell_precise",1,3],["ACE_HuntIR_M203",3,1],["TB_rhs_mag_40mm_HEDP",3,1],["TB_rhs_mag_40mm_HE",3,1],["BWA3_DM25",3,1],["BWA3_DM32_Blue",2,1],["BWA3_DM32_Orange",2,1],["rhs_mag_mk3a2",2,1]]],["OPXT_scorpion_1523",[["ACE_packingBandage",20],["ACE_quikclot",5],["ACE_salineIV_500",1],["ACE_morphine",5],["BWA3_30Rnd_556x45_G36",12,30]]],"BWA3_M92_Multi","",["ACE_Vector","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "grena": {[["BWA3_G36A3_AG40","","BWA3_acc_VarioRay_irlaser_black","BWA3_optic_ZO4x30i_MicroT2",["BWA3_30Rnd_556x45_G36",30],["TB_rhs_mag_40mm_HEDP",1],""],[],[],["BWA3_Uniform_Multi",[["ACE_Flashlight_KSF1",1],["ACE_tourniquet",4],["ACE_HuntIR_monitor",1]]],["BWA3_Vest_Grenadier_Multi",[["ACE_HuntIR_M203",2,1],["TB_rhs_mag_40mm_HEDP",4,1],["3Rnd_Smoke_Grenade_shell_precise",1,3],["rhs_mag_m713_Red_precise",1,1],["BWA3_DM25",3,1],["rhs_mag_mk3a2",1,1],["BWA3_DM32_Blue",1,1],["TB_rhs_mag_40mm_HE",6,1]]],["BWA3_Kitbag_Multi",[["ACE_packingBandage",20],["ACE_morphine",5],["ACE_quikclot",5],["BWA3_30Rnd_556x45_G36",8,30]]],"BWA3_M92_Multi","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "sani": {[["BWA3_G36A3","","BWA3_acc_VarioRay_irlaser_black","BWA3_optic_ZO4x30i_MicroT2",["BWA3_30Rnd_556x45_G36",30],[],"BWA3_bipod_Harris"],[],[],["BWA3_Uniform_Multi",[["ACE_Flashlight_KSF1",1],["adv_aceCPR_AED",1],["ACE_tourniquet",4]]],["BWA3_Vest_Medic_Multi",[["ACE_surgicalKit",1],["ACE_plasmaIV",4],["ACE_morphine",20],["TB_med_thrombin",2],["ACE_quikclot",10],["ACE_tourniquet",10],["BWA3_DM25",3,1],["BWA3_DM32_Blue",1,1],["rhs_mag_mk3a2",1,1]]],["BWA3_Kitbag_Multi_Medic",[["ACE_elasticBandage",40],["ACE_packingBandage",40],["ACE_epinephrine",5],["ACE_plasmaIV_500",4],["BWA3_30Rnd_556x45_G36",9,30]]],"BWA3_M92_Multi","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "mg": {[["BWA3_MG5","","BWA3_acc_VarioRay_irlaser_black","BWA3_optic_ZO4x30i_MicroT2",["BWA3_120Rnd_762x51_soft",120],[],""],[],[],["BWA3_Uniform_Multi",[["ACE_tourniquet",4],["ACE_Flashlight_KSF1",1]]],["BWA3_Vest_MachineGunner_Multi",[["BWA3_DM25",3,1],["BWA3_DM32_Blue",1,1],["rhs_mag_mk3a2",1,1]]],["BWA3_Kitbag_Multi",[["ACE_packingBandage",20],["ACE_quikclot",5],["ACE_morphine",5],["BWA3_120Rnd_762x51_soft",3,120]]],"BWA3_M92_Multi","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "spreng": {[["BWA3_G36A3","","BWA3_acc_VarioRay_irlaser_black","BWA3_optic_ZO4x30i_MicroT2",["BWA3_30Rnd_556x45_G36",30],[],"BWA3_bipod_Harris"],[],[],["BWA3_Uniform_Multi",[["ACE_Flashlight_KSF1",1],["ACE_wirecutter",1]]],["BWA3_Vest_Rifleman_Multi",[["ACE_DefusalKit",1],["ACE_M26_Clacker",1],["ToolKit",1],["BWA3_DM25",3,1],["BWA3_DM32_Blue",1,1],["rhs_mag_mk3a2",1,1],["DemoCharge_Remote_Mag",2,1]]],["BWA3_Kitbag_Multi",[["ACE_packingBandage",20],["ACE_quikclot",5],["ACE_morphine",5],["BWA3_30Rnd_556x45_G36",10,30],["AMP_Breaching_Charge_Mag",2,1],["SLAMDirectionalMine_Wire_Mag",2,1]]],"BWA3_M92_Multi","",["Binocular","","","",[],[],""],["ItemMap","B_UavTerminal","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "aaat": {[["BWA3_G36A3","","BWA3_acc_VarioRay_irlaser_black","BWA3_optic_ZO4x30i_MicroT2",["BWA3_30Rnd_556x45_G36",30],[],"BWA3_bipod_Harris"],["BWA3_CarlGustav","","","BWA3_optic_CarlGustav",["BWA3_CarlGustav_HEAT",1],[],""],[],["BWA3_Uniform_Multi",[["ACE_tourniquet",4],["ACE_Flashlight_KSF1",1]]],["BWA3_Vest_Rifleman_Multi",[["BWA3_DM25",3,1],["rhs_mag_mk3a2",1,1],["BWA3_DM32_Blue",1,1],["BWA3_30Rnd_556x45_G36",10,30]]],["BWA3_Carryall_Multi",[["ACE_packingBandage",20],["ACE_quikclot",5],["ACE_morphine",5],["BWA3_CarlGustav_HEAT",2,1]]],"BWA3_M92_Multi","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "trag": {[["BWA3_G36A3","","BWA3_acc_VarioRay_irlaser_black","BWA3_optic_ZO4x30i_MicroT2",["BWA3_30Rnd_556x45_G36",30],[],"BWA3_bipod_Harris"],[],[],["BWA3_Uniform_Multi",[["ACE_Flashlight_KSF1",1],["ACE_tourniquet",4]]],["BWA3_Vest_Rifleman_Multi",[["BWA3_DM25",3,1],["BWA3_DM32_Blue",1,1],["rhs_mag_mk3a2",1,1]]],["BWA3_PatrolPack_Multi",[["BWA3_30Rnd_556x45_G36",20,30]]],"BWA3_M92_Multi","",["ACE_Vector","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "dmr": {[]};
        case "pilot": {[[],[],["BWA3_MP7","BWA3_muzzle_snds_Rotex_II","BWA3_acc_VarioRay_irlaser_black","BWA3_optic_EOTech552",["BWA3_40Rnd_46x30_MP7",40],[],""],["BWA3_Uniform_Crew_Multi",[["ACE_tourniquet",4],["ACE_Flashlight_KSF1",1],["adv_aceCPR_AED",1]]],["BWA3_Vest_JPC_Radioman_Multi",[["ToolKit",1],["ACE_surgicalKit",1],["BWA3_DM25",3,1],["BWA3_DM32_Blue",2,1],["BWA3_DM32_Orange",2,1],["rhs_mag_mk3a2",1,1]]],["OPXT_scorpion_1523",[["ACE_plasmaIV_500",2],["ACE_packingBandage",20],["ACE_quikclot",10],["ACE_epinephrine",2],["ACE_morphine",5],["TB_med_thrombin",2],["BWA3_40Rnd_46x30_MP7_SD",5,40]]],"BWA3_Knighthelm","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "sniper": {[["BWA3_G29","BWA3_muzzle_snds_Rotex_Monoblock","BWA3_acc_VarioRay_irlaser","BWA3_optic_M5Xi_MSR",["BWA3_10Rnd_86x70_G29",10],[],"BWA3_bipod_Harris"],[],[],["BWA3_Uniform_Multi",[["ACE_Flashlight_KSF1",1],["ACE_Kestrel4500",1],["ACE_ATragMX",1],["ACE_RangeCard",1],["ACE_tourniquet",4]]],["BWA3_Vest_JPC_Radioman_Multi",[["ACE_Tripod",1],["ACE_wirecutter",1],["BWA3_DM25",3,1],["BWA3_DM32_Blue",2,1],["BWA3_DM32_Orange",2,1],["rhs_mag_mk3a2",1,1]]],["BWA3_Kitbag_Multi",[["ACE_quikclot",30],["ACE_packingBandage",10],["ACE_morphine",5],["ACE_salineIV_500",1],["BWA3_10Rnd_86x70_G29",6,10]]],"BWA3_M92_Multi","",["ACE_Vector","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "spotter": {[["BWA3_G36A3_AG40","BWA3_muzzle_snds_QDSS","BWA3_acc_VarioRay_irlaser_black","BWA3_optic_ZO4x30i_MicroT2",["BWA3_30Rnd_556x45_G36",30],["1Rnd_HE_Grenade_shell",1],""],[],[],["BWA3_Uniform_Multi",[["ACE_ATragMX",1],["ACE_RangeCard",1],["ACE_HuntIR_monitor",1],["ACE_Flashlight_KSF1",1],["ACE_Kestrel4500",1],["ACE_tourniquet",4],["ACE_DefusalKit",1]]],["BWA3_Vest_Marksman_Fleck",[["BWA3_DM25",3,1],["BWA3_DM32_Blue",2,1],["BWA3_DM32_Orange",2,1],["rhs_mag_mk3a2",1,1],["ACE_HuntIR_M203",2,1],["TB_rhs_mag_40mm_HE",2,1],["rhs_mag_m713_Red_precise",1,1],["3Rnd_Smoke_Grenade_shell_precise",1,3]]],["OPXT_scorpion_1523",[["ACE_quikclot",30],["ACE_packingBandage",10],["ACE_morphine",5],["ACE_salineIV_500",1],["BWA3_30Rnd_556x45_G36",8,30]]],"BWA3_M92_Multi","",["Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "jtac": {[["BWA3_G36A3","","BWA3_acc_VarioRay_irlaser_black","BWA3_optic_ZO4x30i_MicroT2",["BWA3_30Rnd_556x45_G36",30],[],"BWA3_bipod_Harris"],[],[],["BWA3_Uniform_Multi",[["ACE_Flashlight_KSF1",1],["ACE_tourniquet",4]]],["BWA3_Vest_Rifleman_Multi",[["ACE_packingBandage",20],["ACE_quikclot",5],["ACE_morphine",5],["BWA3_DM25",3,1],["BWA3_DM32_Blue",1,1],["BWA3_DM32_Orange",1,1],["rhs_mag_mk3a2",1,1],["BWA3_30Rnd_556x45_G36",10,30]]],["OPXT_scorpion_1523",[]],"BWA3_M92_Multi","",["Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","B_UavTerminal","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "arzt": {[[],[],["BWA3_MP7","","BWA3_acc_VarioRay_irlaser_black","BWA3_optic_MicroT2",["BWA3_40Rnd_46x30_MP7",40],[],""],["BWA3_Uniform_sleeves_Multi",[["ACE_tourniquet",4],["adv_aceCPR_AED",1],["ACE_Flashlight_KSF1",1]]],["BWA3_Vest_Medic_Multi",[["ACE_surgicalKit",1],["BWA3_DM25",3,1],["BWA3_DM32_Blue",1,1],["BWA3_DM32_Orange",1,1],["rhs_mag_mk3a2",1,1]]],["BWA3_Kitbag_Multi_Medic",[["ACE_packingBandage",60],["ACE_quikclot",20],["ACE_elasticBandage",60],["ACE_bloodIV",1],["ACE_bloodIV_500",2],["ACE_bloodIV_250",4],["ACE_tourniquet",15],["ACE_morphine",15],["ACE_epinephrine",5],["TB_med_thrombin",5],["BWA3_40Rnd_46x30_MP7",4,40]]],"TB_helmet_Sani_C_Green","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "rifle" : {[["BWA3_G28","","BWA3_acc_VarioRay_irlaser","BWA3_optic_PMII_DMR_MicroT1_rear",["BWA3_10Rnd_762x51_G28",10],[],""],[],[],["BWA3_Uniform_Multi",[["ACE_tourniquet",4],["ACE_RangeCard",1],["ACE_Kestrel4500",1],["ACE_Flashlight_KSF1",1]]],["BWA3_Vest_Marksman_Multi",[["BWA3_DM25",3,1],["BWA3_DM32_Blue",1,1],["BWA3_DM32_Orange",1,1],["rhs_mag_mk3a2",1,1]]],["BWA3_Kitbag_Multi",[["ACE_packingBandage",20],["ACE_quikclot",5],["ACE_morphine",5],["BWA3_10Rnd_762x51_G28",10,10]]],"BWA3_M92_Multi","",["ACE_Vector","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "pionier" : {[["BWA3_G36A3","","BWA3_acc_VarioRay_irlaser_black","BWA3_optic_ZO4x30i_MicroT2",["BWA3_30Rnd_556x45_G36",30],[],"BWA3_bipod_Harris"],[],[],["BWA3_Uniform_Multi",[["ACE_tourniquet",4],["ACE_DefusalKit",1],["ACE_wirecutter",1],["ACE_Flashlight_KSF1",1]]],["BWA3_Vest_Rifleman_Multi",[["ACE_EntrenchingTool",1],["ToolKit",1],["ACE_M26_Clacker",1],["BWA3_DM25",3,1],["BWA3_DM32_Blue",1,1],["BWA3_DM32_Orange",1,1],["rhs_mag_mk3a2",1,1]]],["BWA3_Kitbag_Multi",[["ACE_packingBandage",20],["ACE_quikclot",5],["ACE_morphine",5],["BWA3_30Rnd_556x45_G36",10,30],["DemoCharge_Remote_Mag",3,1]]],"BWA3_M92_Multi","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        default {[]};
    };

    ACE_player setUnitLoadout [_layout, true];
};

if (_arsenalType == "VANILLA") exitWith
{
    private _layout = switch (_rolle) do
    {
        case "lead": {[["arifle_MX_GL_Black_F","","ACE_acc_pointer_green","optic_ERCO_blk_F",["30Rnd_65x39_caseless_mag_Tracer",30],["ACE_HuntIR_M203",1],""],[],["hgun_Pistol_heavy_01_F","muzzle_snds_acp","","optic_MRD",["11Rnd_45ACP_Mag",11],[],""],["U_B_CTRG_1",[["ACE_packingBandage",25],["ACE_morphine",10],["ACE_tourniquet",4]]],["V_PlateCarrier2_blk",[["ACE_MapTools",1],["ACE_Flashlight_KSF1",1],["ACE_EntrenchingTool",1],["ACE_CableTie",2],["ACE_HuntIR_monitor",1],["30Rnd_65x39_caseless_mag_Tracer",10,30],["Laserbatteries",1,1]]],["OPXT_blk_1523",[["1Rnd_Smoke_Grenade_shell",6,1],["1Rnd_SmokePurple_Grenade_shell",2,1],["ACE_HuntIR_M203",5,1]]],"H_HelmetSpecB","G_Bandanna_beast",["Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","ItemGPS","TFAR_anprc152_27","ItemCompass","ACE_Altimeter",""]]};
        case "grena": {[["arifle_MX_GL_Black_F","","ACE_acc_pointer_green","optic_ERCO_blk_F",["30Rnd_65x39_caseless_mag_Tracer",30],["1Rnd_Smoke_Grenade_shell",1],""],[],["hgun_Pistol_heavy_01_F","muzzle_snds_acp","","optic_MRD",["11Rnd_45ACP_Mag",11],[],""],["U_B_CTRG_1",[["ACE_packingBandage",25],["ACE_morphine",10],["ACE_tourniquet",4]]],["V_PlateCarrier2_blk",[["ACE_CableTie",2],["ACE_MapTools",1],["ACE_Flashlight_KSF1",1],["ACE_EntrenchingTool",1],["ACE_HuntIR_monitor",1],["30Rnd_65x39_caseless_mag_Tracer",10,30]]],["B_Kitbag_rgr",[["ACE_salineIV_250",4],["3Rnd_Smoke_Grenade_shell",6,3],["3Rnd_HE_Grenade_shell",6,3]]],"H_HelmetSpecB","G_Bandanna_beast",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152_28","ItemCompass","ACE_Altimeter",""]]};
        case "arzt": {[[],[],["hgun_Pistol_heavy_01_F","muzzle_snds_acp","","optic_MRD",["11Rnd_45ACP_Mag",11],[],""],["U_B_CTRG_1",[["ACE_surgicalKit",1],["ACE_quikclot",25]]],["V_PlateCarrier2_blk",[["ACE_tourniquet",6],["ACE_elasticBandage",35],["ACE_packingBandage",50],["ACE_morphine",10],["ACE_epinephrine",10],["ACE_morphine",10],["ACE_MapTools",1],["ACE_Flashlight_KSF1",1],["ACE_CableTie",2]]],["B_Kitbag_sgg",[["ACE_bloodIV",10],["ACE_bloodIV_500",5],["adv_aceCPR_AED",1],["ACE_EntrenchingTool",1],["ACE_personalAidKit",1],["SmokeShellRed",8,1]]],"H_HelmetSpecB","G_Bandanna_beast",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
        case "sani": {[["arifle_MX_Black_F","muzzle_snds_H","ACE_acc_pointer_green","optic_ERCO_blk_F",["30Rnd_65x39_caseless_mag_Tracer",30],[],"bipod_01_F_blk"],[],["hgun_Pistol_heavy_01_F","muzzle_snds_acp","","optic_MRD",["11Rnd_45ACP_Mag",11],[],""],["U_B_CTRG_1",[["ACE_surgicalKit",1],["ACE_quikclot",25]]],["V_PlateCarrier2_blk",[["ACE_elasticBandage",35],["ACE_packingBandage",50],["ACE_epinephrine",10],["ACE_morphine",10],["ACE_morphine",10],["ACE_tourniquet",6],["ACE_CableTie",4]]],["B_Kitbag_rgr",[["ACE_plasmaIV",10],["ACE_plasmaIV_500",5],["adv_aceCPR_AED",1],["30Rnd_65x39_caseless_mag_Tracer",10,30],["11Rnd_45ACP_Mag",3,11]]],"H_HelmetSpecB_sand","G_Bandanna_beast",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152_33","ItemCompass","ACE_Altimeter",""]]};
        case "mg": {[["LMG_03_F","","ACE_acc_pointer_green_IR","optic_ERCO_blk_F",["200Rnd_556x45_Box_F",200],[],""],[],["hgun_Pistol_heavy_01_F","muzzle_snds_acp","","optic_MRD",["11Rnd_45ACP_Mag",11],[],""],["U_B_CTRG_3",[["ACE_packingBandage",25],["ACE_morphine",10],["ACE_tourniquet",4]]],["V_PlateCarrier2_blk",[["ACE_MapTools",1],["ACE_Flashlight_KSF1",1],["ACE_EntrenchingTool",1],["ACE_salineIV_250",4],["200Rnd_556x45_Box_Tracer_F",2,200]]],["B_Kitbag_rgr",[["200Rnd_556x45_Box_Tracer_F",3,200],["11Rnd_45ACP_Mag",2,11],["SmokeShell",4,1]]],"H_HelmetSpecB","G_Bandanna_beast",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152_30","ItemCompass","ACE_Altimeter",""]]};
        case "spreng": {[["arifle_MX_Black_F","","ACE_acc_pointer_green","optic_ERCO_blk_F",["30Rnd_65x39_caseless_mag",30],[],"bipod_01_F_blk"],[],["ACE_VMM3","","","",[],[],""],["U_B_CTRG_1",[["ACE_packingBandage",25],["ACE_morphine",10],["ACE_tourniquet",4]]],["V_PlateCarrierGL_blk",[["ACE_Flashlight_KSF1",1],["ACE_M26_Clacker",1],["MineDetector",1],["ACE_wirecutter",1],["ACE_DefusalKit",1],["ACE_EntrenchingTool",1],["30Rnd_65x39_caseless_mag_Tracer",7,30]]],["B_Kitbag_rgr",[["DemoCharge_Remote_Mag",6,1]]],"H_HelmetSpecB_sand","G_Bandanna_beast",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152_31","ItemCompass","ACE_Altimeter",""]]} ;
        case "aaat": {[["arifle_MX_Black_F","","ACE_acc_pointer_green","optic_ERCO_blk_F",["30Rnd_65x39_caseless_mag_Tracer",30],[],"bipod_01_F_blk"],["launch_MRAWS_sand_F","","","",["MRAWS_HEAT_F",1],[],""],[],["U_B_CTRG_1",[["ACE_packingBandage",25],["ACE_morphine",10],["ACE_tourniquet",4]]],["V_PlateCarrier2_blk",[["ACE_CableTie",2],["ACE_MapTools",1],["ACE_Flashlight_KSF1",1],["ACE_EntrenchingTool",1],["ACE_salineIV_250",4],["30Rnd_65x39_caseless_mag_Tracer",8,30]]],["B_Kitbag_rgr",[["MRAWS_HEAT_F",4,1],["SmokeShell",5,1]]],"H_HelmetSpecB","G_Bandanna_beast",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152_36","ItemCompass","ACE_Altimeter",""]]};
        case "trag": {[["arifle_MX_Black_F","","ACE_acc_pointer_green","optic_ERCO_blk_F",["30Rnd_65x39_caseless_mag_Tracer",30],[],"bipod_02_F_blk"],[],["hgun_Pistol_heavy_01_F","muzzle_snds_acp","","optic_MRD",["11Rnd_45ACP_Mag",11],[],""],["U_B_CTRG_1",[["ACE_packingBandage",25],["ACE_morphine",10],["ACE_tourniquet",4]]],["V_PlateCarrier2_blk",[["ACE_salineIV_250",4],["30Rnd_65x39_caseless_mag_Tracer",10,30]]],["B_Carryall_cbr",[["MRAWS_HEAT_F",2,1],["20Rnd_762x51_Mag",5,20],["30Rnd_65x39_caseless_mag_Tracer",10,30],["200Rnd_556x45_Box_Tracer_Red_F",1,200]]],"H_HelmetSpecB_sand","G_Bandanna_beast",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152_37","ItemCompass","ACE_Altimeter",""]]} ;
        case "dmr": {[["srifle_EBR_F","","ACE_acc_pointer_green","optic_DMS",["20Rnd_762x51_Mag",20],[],"bipod_01_F_snd"],[],["hgun_Pistol_heavy_01_F","muzzle_snds_acp","","optic_MRD",["11Rnd_45ACP_Mag",11],[],""],["U_B_CTRG_1",[["ACE_packingBandage",25],["ACE_morphine",10],["ACE_tourniquet",4]]],["V_PlateCarrier2_blk",[["ACE_CableTie",4],["ACE_MapTools",1],["ACE_Flashlight_KSF1",1],["ACE_EntrenchingTool",1],["ACE_salineIV_250",4],["20Rnd_762x51_Mag",7,20]]],["B_Kitbag_rgr",[["20Rnd_762x51_Mag",5,20],["11Rnd_45ACP_Mag",3,11],["SmokeShell",4,1]]],"H_HelmetSpecB_sand","G_Bandanna_beast",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152_35","ItemCompass","ACE_Altimeter",""]]};
        case "pilot": {[["SMG_01_F","","","optic_ACO_grn_smg",["30Rnd_45ACP_Mag_SMG_01",25],[],""],[],["hgun_Pistol_heavy_01_F","muzzle_snds_acp","","optic_MRD",["11Rnd_45ACP_Mag",11],[],""],["U_B_HeliPilotCoveralls",[["ACE_surgicalKit",1],["ACE_quikclot",25]]],["V_DeckCrew_white_F",[["adv_aceCPR_AED",1],["30Rnd_45ACP_Mag_SMG_01_Tracer_Yellow",2,25]]],["OPXT_wht_1523",[["ACE_plasmaIV",5],["ACE_elasticBandage",30],["ACE_packingBandage",35],["ACE_epinephrine",10],["ACE_morphine",10],["ACE_morphine",10]]],"H_CrewHelmetHeli_B","G_Bandanna_beast",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152_39","ItemCompass","ACE_Altimeter",""]]};
        case "sniper": {[["srifle_LRR_F","","","optic_LRPS",["7Rnd_408_Mag",7],[],""],[],["hgun_Pistol_heavy_01_F","muzzle_snds_acp","","optic_MRD",["11Rnd_45ACP_Mag",11],[],""],["U_B_FullGhillie_ard",[["ACE_packingBandage",25],["ACE_tourniquet",4],["ACE_morphine",10],["ACE_EntrenchingTool",1],["ACE_ATragMX",1],["ACE_Kestrel4500",1],["ACE_Flashlight_KSF1",1],["ACE_MapTools",1],["ACE_RangeCard",1]]],["V_PlateCarrier2_blk",[["ACE_Tripod",1],["ACE_HuntIR_monitor",1],["7Rnd_408_Mag",5,7],["11Rnd_45ACP_Mag",1,11]]],["OPXT_blk_1523",[["ACE_wirecutter",1],["optic_KHS_blk",1],["optic_AMS",1],["7Rnd_408_Mag",6,7],["SmokeShellPurple",4,1],["Laserbatteries",1,1]]],"H_HelmetSpecB","G_Bandanna_beast",["ACE_Vector","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152_44","ItemCompass","ACE_Altimeter",""]]};
        case "spotter": {[["arifle_MX_GL_F","","","optic_ERCO_snd_F",["30Rnd_65x39_caseless_mag_Tracer",30],["ACE_HuntIR_M203",1],""],[],["hgun_Pistol_heavy_01_F","muzzle_snds_acp","","optic_MRD",["11Rnd_45ACP_Mag",11],[],""],["U_B_FullGhillie_ard",[["ACE_packingBandage",25],["ACE_morphine",10],["ACE_EntrenchingTool",1],["ACE_Flashlight_KSF1",1],["ACE_tourniquet",4],["ACE_RangeCard",1],["ACE_ATragMX",1],["ACE_Kestrel4500",1],["ACE_MapTools",1],["ACE_CableTie",1]]],["V_PlateCarrier2_blk",[["ACE_SpottingScope",1],["ACE_HuntIR_monitor",1],["ACE_wirecutter",1],["30Rnd_65x39_caseless_mag_Tracer",5,30]]],["OPXT_blk_1523",[["ACE_salineIV_250",3],["3Rnd_Smoke_Grenade_shell",5,3],["3Rnd_HE_Grenade_shell",2,3],["ACE_HuntIR_M203",5,1],["Laserbatteries",1,1],["30Rnd_65x39_caseless_mag_Tracer",2,30]]],"H_HelmetSpecB_sand","G_Bandanna_beast",["Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","ItemGPS","TFAR_anprc152_45","ItemCompass","ACE_Altimeter",""]]};
        case "jtac": {[["arifle_MX_GL_Black_F","","","optic_ERCO_blk_F",["30Rnd_65x39_caseless_mag_Tracer",30],[],""],[],["hgun_Pistol_heavy_01_F","muzzle_snds_acp","","optic_MRD",["11Rnd_45ACP_Mag",11],[],""],["U_B_CTRG_1",[["ACE_packingBandage",25],["ACE_morphine",10],["ACE_tourniquet",4]]],["V_PlateCarrier2_blk",[["ACE_MapTools",1],["ACE_Flashlight_KSF1",1],["ACE_UAVBattery",4],["ACE_HuntIR_monitor",1],["Laserbatteries",2,1],["30Rnd_65x39_caseless_mag_Tracer",2,30]]],["B_UAV_01_backpack_F",[]],"H_HelmetSpecB","G_Bandanna_beast",["Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","B_UavTerminal","TFAR_anprc152_4","ItemCompass","ACE_Altimeter",""]]};
        case "rifle" : {[["arifle_MX_F","","ACE_acc_pointer_green","optic_ERCO_snd_F",["30Rnd_65x39_caseless_mag_Tracer",30],[],"bipod_01_F_snd"],[],["hgun_Pistol_heavy_01_F","muzzle_snds_acp","","optic_MRD",["11Rnd_45ACP_Mag",11],[],""],["U_B_CTRG_1",[["ACE_packingBandage",25],["ACE_morphine",10],["ACE_tourniquet",4]]],["V_PlateCarrier2_blk",[["ACE_MapTools",1],["ACE_Flashlight_KSF1",1],["ACE_EntrenchingTool",1],["ACE_wirecutter",1],["ACE_CableTie",2],["ACE_salineIV_250",4],["ACE_packingBandage",20]]],["B_Kitbag_sgg",[["30Rnd_65x39_caseless_mag",10,30],["11Rnd_45ACP_Mag",5,11],["HandGrenade",5,1],["SmokeShell",5,1],["AMP_Breaching_Charge_Mag",5,1]]],"H_HelmetSpecB","G_Bandanna_oli",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152_5","ItemCompass","ACE_Altimeter",""]]};
        case "pionier" : {[["arifle_MX_F","","ACE_acc_pointer_green_IR","optic_ERCO_snd_F",["30Rnd_65x39_caseless_mag_Tracer",30],[],"bipod_01_F_snd"],[],["hgun_Pistol_heavy_01_F","muzzle_snds_acp","","optic_MRD",["11Rnd_45ACP_Mag",11],[],""],["U_B_CTRG_1",[["ACE_tourniquet",4],["ACE_packingBandage",25],["ACE_morphine",10]]],["V_PlateCarrierGL_blk",[["ACE_wirecutter",1],["ACE_DefusalKit",1],["ACE_EntrenchingTool",1],["MineDetector",1],["ACE_CableTie",2],["ACE_MapTools",1],["ACE_Flashlight_KSF1",1],["SmokeShellBlue",2,1],["SmokeShellYellow",2,1],["SmokeShell",2,1],["30Rnd_65x39_caseless_mag_Tracer",5,30]]],["OPXT_blk_1523",[["ToolKit",1],["ACE_salineIV_250",4],["ACE_HuntIR_monitor",1]]],"H_HelmetSpecB","",[],["","","","","",""]]};
        default {[]};
    };

    ACE_player setUnitLoadout [_layout, true];
};

if (_arsenalType == "RUSS") exitWith
{
    private _layout = switch (_rolle) do
    {
                case "lead": {[["rhs_weap_ak74m_zenitco01_b33","rhs_acc_dtk","","optic_MRCO",["rhs_30Rnd_545x39_AK_plum_green",30],[],""],[],[],["rhs_uniform_vdv_emr",[["ACE_packingBandage",25],["ACE_morphine",10],["ACE_tourniquet",4],["ACE_CableTie",2]]],["rhs_6b13_EMR_6sh92",[["ACE_EntrenchingTool",1],["ACE_salineIV_250",1],["ACE_MapTools",1],["rhs_mag_rdg2_white",4,1],["AMP_Breaching_Charge_Mag",2,1],["rhs_mag_nspd",2,1]]],["OPXT_multicamt_117",[["rhs_30Rnd_545x39_AK_plum_green",10,30]]],"rhs_6b47_ess","",["rhs_pdu4","","","",[],[],""],["ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ACE_Altimeter",""]]};
                case "grena": {[["rhs_weap_ak74mr_gp25","rhs_acc_uuk","","",["rhs_30Rnd_545x39_AK_plum_green",30],["rhs_VG40TB",1],""],[],[],["rhs_uniform_vdv_emr",[["ACE_packingBandage",25],["ACE_morphine",10],["ACE_tourniquet",4],["ACE_CableTie",2]]],["rhs_6b23_6sh116_vog",[["ACE_EntrenchingTool",1],["ACE_salineIV_250",1],["rhs_mag_rdg2_white",5,1],["AMP_Breaching_Charge_Mag",2,1],["rhs_GRD40_White",9,1],["rhs_VG40TB",8,1]]],["rhs_assault_umbts",[["rhs_30Rnd_545x39_AK_plum_green",10,30],["rhs_VG40SZ",2,1],["rhs_VOG25",2,1],["rhs_VOG25P",2,1]]],"rhs_6b47_ess","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ACE_Altimeter",""]]};
                case "sani": {[["rhs_weap_ak74m_zenitco01_b33","rhs_acc_dtk1983","","",["rhs_30Rnd_545x39_AK_plum_green",30],[],""],[],[],["rhs_uniform_vdv_emr",[["ACE_CableTie",2],["ACE_quikclot",30],["ACE_tourniquet",8]]],["rhs_6b23_digi_medic",[["ACE_epinephrine",10],["ACE_morphine",10],["adv_aceCPR_AED",1],["ACE_surgicalKit",1],["ACE_plasmaIV",4],["ACE_plasmaIV_500",2],["ACE_plasmaIV_250",2]]],["rhs_assault_umbts",[["ACE_elasticBandage",40],["ACE_packingBandage",40],["rhs_30Rnd_545x39_AK_plum_green",4,30],["rhs_mag_rdg2_white",2,1]]],"rhs_6b47_ess","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ACE_Altimeter",""]]};
                case "mg": {[["rhs_weap_pkp","","","rhs_acc_pkas",["rhs_100Rnd_762x54mmR_green",100],[],""],[],[],["rhs_uniform_vdv_emr",[["ACE_packingBandage",25],["ACE_morphine",10],["ACE_tourniquet",4],["ACE_CableTie",2]]],["rhs_6b13_EMR_6sh92",[["ACE_EntrenchingTool",1],["ACE_salineIV_250_500",1],["AMP_Breaching_Charge_Mag",2,1],["rhs_100Rnd_762x54mmR_green",1,100]]],["B_Carryall_oli",[["rhs_100Rnd_762x54mmR_green",4,100],["rhs_mag_rdg2_white",5,1]]],"rhs_6b47_ess","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ACE_Altimeter",""]]};
                case "spreng": {[["rhs_weap_ak74mr","rhs_acc_dtk","","",["rhs_30Rnd_545x39_AK_plum_green",30],[],""],[],[],["rhs_uniform_vdv_emr",[["ACE_packingBandage",25],["ACE_morphine",10],["ACE_tourniquet",4],["ACE_CableTie",2]]],["rhs_6b13_EMR_6sh92",[["ACE_EntrenchingTool",1],["ACE_M26_Clacker",1],["ACE_DefusalKit",1],["rhs_mag_rdg2_white",4,1],["AMP_Breaching_Charge_Mag",2,1],["DemoCharge_Remote_Mag",2,1]]],["rhs_assault_umbts_engineer_empty",[["ACE_wirecutter",1],["DemoCharge_Remote_Mag",2,1],["AMP_Breaching_Charge_Mag",2,1],["rhs_30Rnd_545x39_AK_plum_green",6,30],["rhs_mag_rdg2_white",2,1]]],"rhs_6b47_ess","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ACE_Altimeter",""]]};
                case "aaat": {[["rhs_weap_ak74m_zenitco01_b33","rhs_acc_dtk","","",["rhs_30Rnd_545x39_AK_plum_green",30],[],""],["rhs_weap_rpg7","","","rhs_acc_pgo7v3",["rhs_rpg7_PG7VR_mag",1],[],""],[],["rhs_uniform_vdv_emr",[["ACE_packingBandage",25],["ACE_morphine",10],["ACE_tourniquet",4],["ACE_CableTie",2]]],["rhs_6b13_EMR_6sh92",[["ACE_EntrenchingTool",1],["ACE_salineIV_250",1],["rhs_mag_rdg2_white",5,1],["AMP_Breaching_Charge_Mag",2,1]]],["B_Carryall_oli",[["rhs_rpg7_PG7VL_mag",2,1],["rhs_rpg7_OG7V_mag",2,1],["rhs_rpg7_PG7VR_mag",1,1],["rhs_30Rnd_545x39_AK_plum_green",8,30]]],"rhs_6b47_ess","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ACE_Altimeter",""]]};
                case "trag": {[["rhs_weap_ak74m_zenitco01_b33","rhs_acc_dtk","","",["rhs_30Rnd_545x39_AK_plum_green",30],[],""],[],[],["rhs_uniform_vdv_emr",[["ACE_packingBandage",25],["ACE_morphine",10],["ACE_tourniquet",4],["ACE_CableTie",2]]],["rhs_6b13_Flora_6sh92_vog",[["ACE_EntrenchingTool",1],["ACE_salineIV_250",1],["rhs_mag_rdg2_white",5,1],["AMP_Breaching_Charge_Mag",2,1],["rhs_30Rnd_545x39_AK_plum_green",3,30]]],["TB_backpacks_bergen_m81",[["rhs_100Rnd_762x54mmR_green",4,100],["rhs_rpg7_PG7VL_mag",1,1],["rhs_30Rnd_545x39_AK_plum_green",22,30]]],"rhs_6b47_ess","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ACE_Altimeter",""]]};
                case "dmr": {[]};
                case "pilot": {[["rhs_weap_pp2000","","","",["rhs_mag_9x19mm_7n21_20",20],[],""],[],[],["rhs_uniform_vdv_emr",[["ACE_CableTie",2],["ACE_quikclot",30],["ACE_tourniquet",8]]],["rhs_6b13_EMR_6sh92",[["ACE_epinephrine",10],["ACE_morphine",10],["ACE_morphine",10],["ACE_surgicalKit",1],["adv_aceCPR_AED",1],["ACE_MapTools",1],["ACE_Flashlight_KSF1",1],["ACE_CableTie",2]]],["OPXT_ogao_210",[["ToolKit",1],["ACE_plasmaIV",3],["ACE_plasmaIV_250",3],["ACE_plasmaIV_500",3],["ACE_elasticBandage",50],["ACE_packingBandage",50],["ACE_bodyBag",1],["rhs_mag_9x19mm_7n31_44",3,44]]],"rhs_tsh4","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ACE_Altimeter",""]]};
                case "sniper": {[[],[],[],["rhs_uniform_vdv_emr",[["ACE_packingBandage",25],["ACE_morphine",10],["ACE_tourniquet",4],["ACE_CableTie",2]]],["rhs_6b13_EMR_6sh92",[["ACE_EntrenchingTool",1],["ACE_salineIV_250",1],["rhs_mag_rdg2_white",5,1],["AMP_Breaching_Charge_Mag",2,1]]],["rhs_assault_umbts",[]],"rhs_6b47_ess","",["rhs_pdu4","","","",[],[],""],["ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ACE_Altimeter",""]]};
                case "spotter": {[[],[],[],["rhs_uniform_vdv_emr",[["ACE_packingBandage",25],["ACE_morphine",10],["ACE_tourniquet",4],["ACE_CableTie",2]]],["rhs_6b13_EMR_6sh92",[["ACE_EntrenchingTool",1],["ACE_salineIV_250",1],["rhs_mag_rdg2_white",5,1],["AMP_Breaching_Charge_Mag",2,1]]],["rhs_assault_umbts",[]],"rhs_6b47_ess","",["rhs_pdu4","","","",[],[],""],["ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ACE_Altimeter",""]]};
                case "jtac": {[[],[],[],["rhs_uniform_vdv_emr",[["ACE_packingBandage",25],["ACE_morphine",10],["ACE_tourniquet",4],["ACE_CableTie",2]]],["rhs_6b13_EMR_6sh92",[["ACE_EntrenchingTool",1],["ACE_salineIV_250",1],["rhs_mag_rdg2_white",5,1],["AMP_Breaching_Charge_Mag",2,1]]],[],"rhs_6b47_ess","",["Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ACE_Altimeter",""]]};
                case "arzt": {[["rhs_weap_pp2000","","","",["rhs_mag_9x19mm_7n31_44",44],[],""],[],[],["rhs_uniform_vdv_emr",[["ACE_CableTie",2],["ACE_quikclot",30],["ACE_tourniquet",8]]],["rhs_6b23_digi_medic",[["ACE_epinephrine",10],["ACE_morphine",10],["adv_aceCPR_AED",1],["ACE_surgicalKit",1],["ACE_bloodIV_500",5],["ACE_bloodIV",2],["ACE_bloodIV_250",4]]],["rhs_assault_umbts",[["ACE_elasticBandage",40],["ACE_packingBandage",40],["rhs_mag_rdg2_white",2,1],["rhs_mag_9x19mm_7n31_44",3,44]]],"rhs_6b47_ess","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ACE_Altimeter",""]]};
                case "rifle" : {[["rhs_weap_svdp_wd","","","rhs_acc_pso1m2",["ACE_10Rnd_762x54_Tracer_mag",10],[],""],[],[],["rhs_uniform_vdv_emr",[["ACE_packingBandage",25],["ACE_morphine",10],["ACE_tourniquet",4],["ACE_CableTie",2]]],["rhs_6b13_EMR_6sh92",[["ACE_EntrenchingTool",1],["ACE_salineIV_250",1],["rhs_mag_rdg2_white",5,1],["AMP_Breaching_Charge_Mag",2,1]]],["rhs_assault_umbts",[["ACE_10Rnd_762x54_Tracer_mag",15,10]]],"rhs_6b47_ess","",["rhs_pdu4","","","",[],[],""],["ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ACE_Altimeter",""]]};
                case "pionier" : {[["rhs_weap_ak74mr","","","",["rhs_30Rnd_545x39_AK_plum_green",30],[],""],[],[],["rhs_uniform_vdv_emr",[["ACE_packingBandage",25],["ACE_morphine",10],["ACE_tourniquet",4],["ACE_CableTie",2]]],["rhs_6b13_EMR_6sh92",[["ACE_EntrenchingTool",1],["ACE_DefusalKit",1],["rhs_mag_rdg2_white",4,1],["AMP_Breaching_Charge_Mag",4,1]]],["rhs_assault_umbts_engineer_empty",[["ToolKit",1],["rhs_30Rnd_545x39_AK_plum_green",6,30]]],"rhs_6b47_ess","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ACE_Altimeter",""]]};
                default {[]};
    };

    ACE_player setUnitLoadout [_layout, true];
};

if (_arsenalType == "Themen") exitWith
{
    private _patches = configfile >> "CfgPatches";
    private _side = side ACE_player;

    if (isClass (_patches >> "uns_main")) exitWith
    {
        ACE_player setUnitLoadout [[[],[],[],["UNS_ARMY_BDU_101stAB65pv1",[["ACE_quikclot",15],["ACE_tourniquet",2],["ACE_EntrenchingTool",1]]],["UNS_M1956_A12",[]],[],"UNS_M1_3A","",[],["ItemMap","","","ItemCompass","ItemWatch",""]], true];
    };

    if (_side == blufor) exitWith
    {
        if (worldName in ["gm_weferlingen_summer", "gm_weferlingen_winter"]) then
        {
            // BRD
            private _layout = switch (_rolle) do
            {
                case "lead": {[["gm_c7a1_oli","","","gm_c79a1_oli",["gm_30Rnd_556x45mm_B_T_M856_stanag_gry",30],[],""],[],["gm_p1_blk","","","",["gm_8Rnd_9x19mm_B_DM51_p1_blk",8],[],""],["gm_ge_army_uniform_soldier_parka_80_ols",[["ACE_packingBandage",25],["ACE_tourniquet",4],["ACE_morphine",10]]],["gm_dk_army_vest_m00_wdl_rifleman",[["ACE_MapTools",1],["ACE_CableTie",2],["ACE_Flashlight_KSF1",1],["ACE_EntrenchingTool",1],["AMP_Breaching_Charge_Mag",2,1],["gm_30Rnd_556x45mm_B_T_M856_stanag_gry",10,30]]],["OPXT_ogao_210",[["ACE_salineIV_250",2],["gm_smokeshell_wht_dm25",5,1],["gm_8Rnd_9x19mm_B_DM11_p1_blk",5,8]]],"gm_ge_headgear_beret_crew_red_opcom","",["gm_ferod16_oli","","","",[],[],""],["ItemMap","","TFAR_anprc152","gm_ge_army_conat2","gm_watch_kosei_80",""]]};
                case "grena": {[["gm_g3a3_oli","","","gm_feroz24_blk",["gm_20Rnd_762x51mm_B_T_DM21A1_g3_blk",20],[],""],[],["gm_p1_blk","","","",["gm_8Rnd_9x19mm_B_DM11_p1_blk",8],[],""],["gm_ge_army_uniform_soldier_80_oli",[["ACE_packingBandage",25],["ACE_tourniquet",4],["ACE_morphine",10]]],["gm_dk_army_vest_m00_wdl_rifleman",[["ACE_MapTools",1],["ACE_CableTie",2],["ACE_Flashlight_KSF1",1],["ACE_EntrenchingTool",1],["ACE_wirecutter",1],["AMP_Breaching_Charge_Mag",2,1]]],["gm_ge_army_backpack_80_oli",[["ACE_salineIV_250",2],["gm_20Rnd_762x51mm_B_T_DM21A1_g3_blk",5,20],["gm_20Rnd_762x51mm_AP_DM151_g3_blk",5,20],["gm_8Rnd_9x19mm_B_DM11_p1_blk",5,8],["gm_1rnd_67mm_heat_dm22a1_g3",5,1],["gm_smokeshell_wht_dm25",4,1]]],"gm_dk_headgear_m52_net_oli","",["gm_df7x40_blk","","","",[],[],""],["ItemMap","","TFAR_anprc152","gm_ge_army_conat2","gm_watch_kosei_80",""]]};
                case "sani": {[["gm_c7a1_blk","","","gm_c79a1_blk",["gm_30Rnd_556x45mm_B_M855_stanag_gry",30],[],""],[],[],["gm_ge_army_uniform_soldier_80_oli",[["ACE_quikclot",24],["ACE_tourniquet",10],["TB_med_thrombin",6]]],["gm_dk_army_vest_m00_wdl_rifleman",[["ACE_epinephrine",15],["ACE_morphine",15],["adv_aceCPR_AED",1],["ACE_surgicalKit",1],["gm_30Rnd_556x45mm_B_T_M856_stanag_gry",6,30]]],["gm_ge_army_backpack_80_oli",[["ACE_plasmaIV",10],["ACE_plasmaIV_500",5],["ACE_plasmaIV_250",5],["ACE_elasticBandage",50],["ACE_packingBandage",50]]],"gm_dk_headgear_m52_net_win","",["gm_ferod16_oli","","","",[],[],""],["ItemMap","","TFAR_anprc152","gm_ge_army_conat2","gm_watch_kosei_80",""]]};
                case "arzt": {[["gm_mp5a2_blk","","","",["gm_30Rnd_9x19mm_B_DM51_mp5_blk",30],[],""],[],["gm_lp1_blk","","","",["gm_1Rnd_265mm_flare_single_wht_gc",1],[],""],["gm_ge_army_uniform_soldier_parka_80_oli",[["ACE_packingBandage",25],["ACE_tourniquet",4],["ACE_morphine",10]]],["gm_dk_army_vest_m00_wdl_rifleman",[["ACE_elasticBandage",25],["ACE_packingBandage",50],["ACE_epinephrine",10],["ACE_morphine",10],["ACE_surgicalKit",1],["adv_aceCPR_AED",1],["TB_med_thrombin",10]]],["OPXT_ogag_210",[["ACE_bloodIV",9],["ACE_bloodIV_500",9],["ACE_personalAidKit",1],["ACE_elasticBandage",10],["ACE_packingBandage",10],["gm_1Rnd_265mm_flare_multi_red_gc",2,1],["gm_30Rnd_9x19mm_B_DM51_mp5_blk",5,30],["gm_smokeshell_wht_dm25",7,1]]],"gm_dk_headgear_m52_net_win","",["gm_df7x40_blk","","","",[],[],""],["ItemMap","","TFAR_anprc152","gm_ge_army_conat2","gm_watch_kosei_80",""]]};
                case "pilot": {[["gm_mp2a1_blk","","","",["gm_32Rnd_9x19mm_B_DM51_mp2_blk",32],[],""],[],["gm_lp1_blk","","","",["gm_1Rnd_265mm_flare_multi_red_gc",1],[],""],["gm_ge_pol_uniform_pilot_rolled_grn",[["ACE_quikclot",20],["ACE_epinephrine",10],["ACE_morphine",10]]],["gm_ge_army_vest_pilot_pads_oli",[["ACE_elasticBandage",40],["ACE_packingBandage",40],["ACE_surgicalKit",1]]],["OPXT_ogag_210",[["adv_aceCPR_AED",1],["ACE_plasmaIV",10],["ACE_plasmaIV_250",5],["ACE_plasmaIV_500",5],["ACE_tourniquet",10],["ACE_CableTie",5],["TB_med_thrombin",10],["gm_32Rnd_9x19mm_B_DM51_mp2_blk",5,32],["gm_1Rnd_265mm_flare_multi_red_gc",2,1],["gm_smokeshell_wht_dm25",4,1]]],"gm_ge_headgear_sph4_oli","gm_gc_army_facewear_dustglasses",["gm_ferod16_oli","","","",[],[],""],["ItemMap","","TFAR_anprc152","gm_ge_army_conat2","gm_watch_kosei_80",""]]};
                case "jtac": {[["gm_mp5sd2_blk","","","gm_feroz24_blk",["gm_30Rnd_9x19mm_B_DM51_mp5_blk",30],[],""],[],["ACE_VMH3","","","",[],[],""],["gm_xx_uniform_soldier_bdu_80_wdl",[["ACE_DefusalKit",1],["ACE_M26_Clacker",1],["ACE_tourniquet",4],["ACE_MapTools",1],["ACE_EntrenchingTool",1],["ACE_packingBandage",10],["ACE_morphine",5],["ACE_CableTie",2]]],["gm_ge_army_vest_pilot_pads_oli",[["ACE_packingBandage",25],["ACE_salineIV_500",4],["gm_30Rnd_9x19mm_B_DM51_mp5_blk",5,30]]],["OPXT_ogag_210",[["gm_smokeshell_wht_dm25",6,1],["gm_explosive_plnp_charge",2,1]]],"gm_ge_headgear_beret_crew_blk_armor","",["gm_ferod16_oli","","","",[],[],""],["ItemMap","","TFAR_anprc152","gm_ge_army_conat2","gm_watch_kosei_80",""]]};
                case "mg": {[["gm_mg3_blk","","","",["gm_120Rnd_762x51mm_B_T_DM21A1_mg3_grn",120],[],""],[],["gm_p1_blk","","","",["gm_8Rnd_9x19mm_B_DM11_p1_blk",8],[],""],["gm_ge_army_uniform_soldier_80_oli",[["ACE_packingBandage",30],["ACE_tourniquet",4],["ACE_morphine",6]]],["gm_dk_army_vest_m00_m84_machinegunner",[["ACE_CableTie",2],["ACE_EntrenchingTool",1],["ACE_Flashlight_KSF1",1],["gm_120Rnd_762x51mm_B_T_DM21A1_mg3_grn",2,120],["gm_smokeshell_wht_dm25",2,1]]],["gm_mg3_aatripod_weaponBag",[]],"gm_dk_headgear_m52_net_oli","",["gm_df7x40_blk","","","",[],[],""],["ItemMap","","TFAR_anprc152","gm_ge_army_conat2","gm_watch_kosei_80",""]]};
                case "aaat": {[["gm_c7a1_oli","","","gm_c79a1_oli",["gm_30Rnd_556x45mm_B_M855_stanag_gry",30],[],""],["gm_pzf44_2_oli","","","gm_feroz2x17_pzf44_2_blk",["gm_1Rnd_44x537mm_heat_dm32_pzf44_2",1],[],""],["gm_p1_blk","","","",["gm_8Rnd_9x19mm_B_DM11_p1_blk",8],[],""],["gm_ge_army_uniform_soldier_80_oli",[["ACE_packingBandage",30],["ACE_tourniquet",4],["ACE_morphine",6]]],["gm_dk_army_vest_m00_wdl_rifleman",[["ACE_MapTools",1],["ACE_CableTie",2],["ACE_Flashlight_KSF1",1],["ACE_EntrenchingTool",1],["ACE_wirecutter",1],["gm_smokeshell_wht_dm25",5,1],["gm_8Rnd_9x19mm_B_DM11_p1_blk",5,8],["gm_30Rnd_556x45mm_B_T_M856_stanag_gry",5,30]]],["gm_ge_army_backpack_80_oli",[["gm_1Rnd_44x537mm_heat_dm32_pzf44_2",6,1],["gm_30Rnd_556x45mm_B_T_M856_stanag_gry",5,30]]],"gm_dk_headgear_m52_net_oli","",["gm_df7x40_blk","","","",[],[],""],["ItemMap","","TFAR_anprc152","gm_gc_compass_f73","gm_watch_kosei_80",""]]};
                case "trag": {[["gm_c7a1_oli","","","gm_c79a1_oli",["gm_30Rnd_556x45mm_B_T_M856_stanag_gry",30],[],""],[],[],["gm_ge_army_uniform_soldier_80_oli",[["ACE_packingBandage",30],["ACE_tourniquet",4],["ACE_morphine",6]]],["gm_dk_army_vest_m00_wdl_rifleman",[["ACE_MapTools",1],["ACE_CableTie",2],["ACE_Flashlight_KSF1",1],["ACE_EntrenchingTool",1],["gm_1Rnd_44x537mm_heat_dm32_pzf44_2",2,1],["gm_30Rnd_556x45mm_B_T_M856_stanag_gry",6,30]]],["TB_backpacks_bergen_m81",[["gm_120Rnd_762x51mm_B_T_DM21A1_mg3_grn",6,120],["gm_30Rnd_556x45mm_B_T_M856_stanag_gry",10,30]]],"gm_dk_headgear_m52_net_oli","",["gm_df7x40_blk","","","",[],[],""],["ItemMap","","TFAR_anprc152","gm_ge_army_conat2","gm_watch_kosei_80",""]]};
                case "pionier" : {[["gm_c7a1_oli","","","gm_c79a1_oli",["gm_30Rnd_556x45mm_B_T_M856_stanag_gry",30],[],""],[],["ACE_VMM3","","","",[],[],""],["gm_ge_army_uniform_soldier_80_ols",[["ACE_packingBandage",25],["ACE_tourniquet",4],["ACE_morphine",10]]],["gm_dk_army_vest_m00_wdl_rifleman",[["ACE_MapTools",1],["ACE_CableTie",2],["ACE_Flashlight_KSF1",1],["ACE_M26_Clacker",1],["ACE_DefusalKit",1],["gm_30Rnd_556x45mm_B_T_M856_stanag_gry",10,30]]],["gm_ge_army_backpack_80_oli",[["ToolKit",1],["gm_explosive_petn_charge",4,1]]],"gm_ge_headgear_m62_net","",["gm_df7x40_blk","","","",[],[],""],["ItemMap","","TFAR_anprc152","gm_ge_army_conat2","gm_watch_kosei_80",""]]};
                default {[]};
            };

            ACE_player setUnitLoadout [_layout, true];
        }
        else
        {
            // Vanilla-COP
            //ACE_player setUnitLoadout [[[],[],["TB_weap_taser","","acc_flashlight_pistol","optic_MRD",["TB_mag_taser",3],[],""],["TB_Uniform_Kommissar_U",[["ACE_quikclot",25],["ACE_tourniquet",4],["ACE_CableTie",5]]],["V_TacVest_blk_POLICE",[["AMP_Breaching_Charge_Mag",1,1],["TB_mag_taser",1,3]]],[],"H_Cap_police","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]], true];

            // WoMi Polizei
            private _layout = switch (_rolle) do
            {
                case "lead";
                case "sani": {[[],[],["rhsusf_weap_glock17g4","","acc_flashlight_pistol","",["rhsusf_mag_17Rnd_9x19_JHP",17],[],""],["TB_Uniform_Sek_U",[["ACE_tourniquet",4],["ACE_packingBandage",10],["ACE_morphine",10],["ACE_epinephrine",2]]],["V_TacVest_blk_POLICE",[["ACE_CableTie",6],["rhsusf_mag_17Rnd_9x19_JHP",4,17],["ACE_M84",1,1]]],[],"H_Cap_police","",[],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""]]};
                case "arzt";
                case "rifle": {[["rhs_weap_mk18","","","rhsusf_acc_su230",["rhs_mag_30Rnd_556x45_M855_Stanag",30],[],""],[],["TB_weap_taser","","acc_flashlight_pistol","optic_MRD",["TB_mag_taser",3],[],""],["rhs_uniform_g3_blk",[["ACE_morphine",10],["ACE_CableTie",6],["TB_mag_taser",1,3]]],["TB_vest_SWAT",[["TB_mag_taser",1,3],["rhs_mag_30Rnd_556x45_M855_Stanag",6,30],["ACE_M84",2,1],["SmokeShell",1,1],["AMP_Breaching_Charge_Mag",1,1]]],[],"TB_helmet_SWAT_01","",[],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ItemWatch",""]]};
                default {[]};
            };

            ACE_player setUnitLoadout [_layout, true];
        };
    };

    if (_side == opfor) exitWith
    {
        // RussSimple
        ACE_player setUnitLoadout [[[],[],[],["rhs_uniform_flora_patchless",[["ACE_packingBandage",10],["ACE_quikclot",10],["ACE_tourniquet",4],["ACE_MapTools",1],["ACE_CableTie",1]]],[],[],"rhs_beret_milp","",[],["ItemMap","ItemGPS","TFAR_fadak","ItemCompass","ACE_Altimeter",""]], true];
    };

    if (_side == independent) exitWith
    {       
        // LDF Arsenal
        private _layout = switch (_rolle) do
        {
            case "lead": {[["arifle_MSBS65_F","","ACE_acc_pointer_green","optic_ERCO_khk_F",["30Rnd_65x39_caseless_msbs_mag_Tracer",30],[],""],[],["hgun_Pistol_heavy_01_green_F","muzzle_snds_acp","acc_flashlight_pistol","optic_MRD_black",["11Rnd_45ACP_Mag",11],[],""],["U_I_E_Uniform_01_officer_F",[["ACE_tourniquet",4],["ACE_packingBandage",25],["ACE_morphine",6],["ACE_MapTools",1],["ACE_Flashlight_KSF1",1]]],["V_CarrierRigKBT_01_light_Olive_F",[["ACE_EntrenchingTool",1],["ACE_HuntIR_monitor",1],["ACE_salineIV_500",2],["SmokeShell",5,1],["SmokeShellGreen",2,1],["SmokeShellBlue",2,1],["AMP_Breaching_Charge_Mag",2,1],["I_E_IR_Grenade",2,1],["HandGrenade",2,1]]],["B_RadioBag_01_eaf_F",[["30Rnd_65x39_caseless_msbs_mag_Tracer",6,30],["11Rnd_45ACP_Mag",2,11]]],"H_HelmetHBK_headset_F","",["Laserdesignator_01_khk_F","","","",["Laserbatteries",1],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
            case "grena": {[["arifle_MSBS65_GL_camo_F","","","optic_ERCO_khk_F",["30Rnd_65x39_caseless_msbs_mag_Tracer",30],["1Rnd_HE_Grenade_shell",1],""],[],["hgun_Pistol_heavy_01_green_F","muzzle_snds_acp","acc_flashlight_pistol","optic_MRD_black",["11Rnd_45ACP_Mag",11],[],""],["U_I_E_Uniform_01_tanktop_F",[["ACE_morphine",6],["ACE_tourniquet",4],["ACE_packingBandage",25],["ACE_MapTools",1],["ACE_Flashlight_KSF1",1]]],["V_CarrierRigKBT_01_light_Olive_F",[["1Rnd_HE_Grenade_shell",14,1],["3Rnd_Smoke_Grenade_shell_precise",3,3],["ACE_HuntIR_M203",3,1]]],["B_Kitbag_sgg",[["ACE_wirecutter",1],["ACE_EntrenchingTool",1],["30Rnd_65x39_caseless_msbs_mag_Tracer",10,30],["11Rnd_45ACP_Mag",4,11],["AMP_Breaching_Charge_Mag",4,1]]],"H_HelmetHBK_headset_F","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
            case "arzt": {[["SMG_03C_TR_camo","","","optic_ACO_grn",["50Rnd_570x28_SMG_03",50],[],""],[],["hgun_Pistol_heavy_01_green_F","muzzle_snds_acp","acc_flashlight_pistol","optic_MRD_black",["11Rnd_45ACP_Mag",11],[],""],["U_I_E_Uniform_01_sweater_F",[["ACE_morphine",15],["ACE_epinephrine",15],["ACE_tourniquet",10]]],["V_CarrierRigKBT_01_light_EAF_F",[["adv_aceCPR_AED",1],["ACE_surgicalKit",1],["ACE_bloodIV",4],["ACE_bloodIV_500",7],["ACE_bloodIV_250",4]]],["B_Kitbag_sgg",[["ACE_elasticBandage",60],["ACE_packingBandage",60],["ACE_quikclot",30],["ACE_morphine",10],["ACE_epinephrine",10],["TB_med_thrombin",10],["50Rnd_570x28_SMG_03",6,50],["11Rnd_45ACP_Mag",2,11]]],"H_HelmetHBK_ear_F","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
            case "sani": {[["arifle_MSBS65_camo_F","","","optic_ERCO_khk_F",["30Rnd_65x39_caseless_msbs_mag_Tracer",30],[],""],[],["hgun_Pistol_heavy_01_green_F","muzzle_snds_acp","acc_flashlight_pistol","optic_MRD_black",["11Rnd_45ACP_Mag",11],[],""],["U_I_E_Uniform_01_sweater_F",[["ACE_morphine",15],["ACE_epinephrine",15],["ACE_tourniquet",10]]],["V_CarrierRigKBT_01_light_EAF_F",[["adv_aceCPR_AED",1],["ACE_surgicalKit",1],["ACE_plasmaIV",6],["ACE_plasmaIV_500",4],["ACE_plasmaIV_250",2]]],["B_Kitbag_sgg",[["ACE_elasticBandage",60],["ACE_packingBandage",60],["ACE_quikclot",30],["ACE_morphine",5],["ACE_epinephrine",5],["TB_med_thrombin",5],["30Rnd_65x39_caseless_msbs_mag_Tracer",10,30],["11Rnd_45ACP_Mag",2,11]]],"H_HelmetHBK_ear_F","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
            case "mg": {[["LMG_03_F","","","optic_ERCO_blk_F",["200Rnd_556x45_Box_Tracer_F",200],[],""],[],[],["U_I_E_Uniform_01_F",[["ACE_packingBandage",25],["ACE_tourniquet",4],["ACE_morphine",6],["ACE_MapTools",1],["ACE_Flashlight_KSF1",1]]],["V_CarrierRigKBT_01_light_EAF_F",[["ACE_EntrenchingTool",1],["ACE_wirecutter",1],["HandGrenade",2,1],["SmokeShell",5,1],["AMP_Breaching_Charge_Mag",2,1]]],["B_Kitbag_sgg",[["200Rnd_556x45_Box_Tracer_F",6,200]]],"H_HelmetHBK_headset_F","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
            case "spreng": {[]};
            case "aaat": {[["arifle_MSBS65_camo_F","","","optic_ERCO_khk_F",["30Rnd_65x39_caseless_msbs_mag_Tracer",30],[],""],["launch_MRAWS_olive_F","","acc_pointer_IR","",["MRAWS_HEAT_F",1],[],""],[],["U_I_E_Uniform_01_F",[["ACE_tourniquet",4],["ACE_morphine",6],["ACE_quikclot",25],["ACE_Flashlight_KSF1",1],["ACE_MapTools",1]]],["V_CarrierRigKBT_01_light_EAF_F",[["30Rnd_65x39_caseless_msbs_mag_Tracer",9,30],["SmokeShell",5,1],["HandGrenade",2,1]]],["B_Kitbag_rgr",[["MRAWS_HEAT_F",4,1],["MRAWS_HE_F",1,1]]],"H_HelmetHBK_ear_F","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
            case "trag": {[["arifle_MSBS65_camo_F","","","optic_ERCO_khk_F",["30Rnd_65x39_caseless_msbs_mag_Tracer",30],[],""],[],["hgun_Pistol_heavy_01_green_F","muzzle_snds_acp","acc_flashlight_pistol","optic_MRD_black",["11Rnd_45ACP_Mag",11],[],""],["U_I_E_Uniform_01_sweater_F",[["ACE_packingBandage",25],["ACE_tourniquet",4],["ACE_morphine",6],["ACE_MapTools",1],["ACE_Flashlight_KSF1",1]]],["V_CarrierRigKBT_01_light_EAF_F",[["30Rnd_65x39_caseless_msbs_mag_Tracer",10,30],["SmokeShell",5,1],["11Rnd_45ACP_Mag",1,11]]],["TB_backpacks_bergen_m81",[["MRAWS_HEAT_F",4,1],["200Rnd_556x45_Box_Tracer_F",3,200],["30Rnd_65x39_caseless_msbs_mag_Tracer",14,30]]],"H_HelmetHBK_headset_F","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
            case "dmr": {[]};
            case "pilot": {[["SMG_01_F","muzzle_snds_acp","","optic_Holosight_arid_F",["30Rnd_45ACP_Mag_SMG_01_Tracer_Green",25],[],""],[],["hgun_Pistol_heavy_01_green_F","muzzle_snds_acp","acc_flashlight_pistol","optic_MRD_black",["11Rnd_45ACP_Mag",11],[],""],["U_I_E_Uniform_01_coveralls_F",[["ACE_tourniquet",10],["ACE_morphine",15],["ACE_epinephrine",15]]],["V_CarrierRigKBT_01_light_Olive_F",[["adv_aceCPR_AED",1],["ACE_surgicalKit",1],["ACE_plasmaIV",5],["ACE_plasmaIV_250",5],["ACE_plasmaIV_500",4]]],["B_RadioBag_01_eaf_F",[["ACE_quikclot",25],["ACE_elasticBandage",14],["ACE_packingBandage",14],["30Rnd_45ACP_Mag_SMG_01_Tracer_Green",2,25],["11Rnd_45ACP_Mag",1,11]]],"H_PilotHelmetFighter_I_E","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
            case "sniper": {[["srifle_LRR_tna_F","","","optic_KHS_blk",["TB_mag_7Rnd_M200_Tracer",7],[],""],[],["hgun_Pistol_heavy_01_green_F","muzzle_snds_acp","acc_flashlight_pistol","optic_MRD_black",["11Rnd_45ACP_Mag",11],[],""],["U_B_FullGhillie_lsh",[["ACE_packingBandage",30],["ACE_quikclot",10],["ACE_morphine",6],["ACE_tourniquet",4],["ACE_RangeCard",1],["ACE_ATragMX",1],["ACE_MapTools",1],["ACE_Kestrel4500",1],["ACE_Flashlight_KSF1",1]]],["V_CarrierRigKBT_01_light_EAF_F",[["ACE_EntrenchingTool",1],["ACE_Tripod",1],["ACE_SpottingScope",1],["SmokeShell",5,1]]],["B_Kitbag_sgg",[["TB_mag_7Rnd_M200_Tracer",17,7],["11Rnd_45ACP_Mag",5,11]]],"H_HelmetHBK_headset_F","",["Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
            case "spotter": {[["arifle_MSBS65_GL_camo_F","muzzle_snds_65_TI_ghex_F","","optic_ERCO_khk_F",["30Rnd_65x39_caseless_msbs_mag_Tracer",30],["ACE_HuntIR_M203",1],""],[],["hgun_Pistol_heavy_01_green_F","muzzle_snds_acp","acc_flashlight_pistol","optic_MRD_black",["11Rnd_45ACP_Mag",11],[],""],["U_B_FullGhillie_lsh",[["ACE_packingBandage",30],["ACE_quikclot",10],["ACE_morphine",6],["ACE_tourniquet",4],["ACE_RangeCard",1],["ACE_Kestrel4500",1],["ACE_MapTools",1],["ACE_Flashlight_KSF1",1],["ACE_ATragMX",1]]],["V_CarrierRigKBT_01_light_Olive_F",[["ACE_DefusalKit",1],["ACE_HuntIR_monitor",1],["ACE_M26_Clacker",1],["ACE_HuntIR_M203",5,1],["TB_rhs_mag_40mm_IR_Grenade",2,1],["3Rnd_Smoke_Grenade_shell_precise",3,3]]],["B_Kitbag_rgr",[["30Rnd_65x39_caseless_msbs_mag_Tracer",8,30],["11Rnd_45ACP_Mag",4,11],["APERSMineDispenser_Mag",2,1]]],"H_HelmetHBK_headset_F","",["Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","ItemGPS","TFAR_anprc152_26","ItemCompass","ACE_Altimeter",""]]};
            case "jtac": {[["arifle_MSBS65_camo_F","","","optic_ERCO_khk_F",["30Rnd_65x39_caseless_msbs_mag_Tracer",30],[],""],[],["hgun_Pistol_heavy_01_green_F","muzzle_snds_acp","acc_flashlight_pistol","optic_MRD_black",["11Rnd_45ACP_Mag",11],[],""],["U_B_CombatUniform_tshirt_mcam_wdL_f",[["ACE_packingBandage",25],["ACE_tourniquet",4],["ACE_morphine",6],["ACE_MapTools",1],["ACE_Flashlight_KSF1",1]]],["V_CarrierRigKBT_01_light_Olive_F",[["ACE_EntrenchingTool",1],["SmokeShell",5,1],["30Rnd_65x39_caseless_msbs_mag_Tracer",5,30],["11Rnd_45ACP_Mag",2,11]]],["I_E_UAV_01_backpack_F",[]],"H_HelmetHBK_headset_F","",["Binocular","","","",[],[],""],["ItemMap","I_E_UavTerminal","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
            case "rifle" : {[["arifle_MSBS65_UBS_camo_F","","","optic_ERCO_blk_F",["30Rnd_65x39_caseless_msbs_mag_Tracer",30],["6Rnd_12Gauge_Slug",6],""],[],["hgun_Pistol_heavy_01_green_F","muzzle_snds_acp","acc_flashlight_pistol","optic_MRD_black",["11Rnd_45ACP_Mag",11],[],""],["U_I_E_Uniform_01_sweater_F",[["ACE_packingBandage",25],["ACE_morphine",6],["ACE_tourniquet",4],["ACE_Flashlight_KSF1",1],["ACE_MapTools",1]]],["V_CarrierRigKBT_01_light_Olive_F",[["ACE_EntrenchingTool",1],["SmokeShell",5,1],["HandGrenade",2,1],["AMP_Breaching_Charge_Mag",2,1],["6Rnd_12Gauge_Slug",4,6],["6Rnd_12Gauge_Pellets",3,6]]],["B_Kitbag_rgr",[["30Rnd_65x39_caseless_msbs_mag_Tracer",10,30],["6Rnd_12Gauge_Slug",5,6],["6Rnd_12Gauge_Pellets",5,6],["11Rnd_45ACP_Mag",2,11]]],"H_HelmetHBK_headset_F","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
            case "pionier" : {[["arifle_MSBS65_camo_F","","","optic_ERCO_khk_F",["30Rnd_65x39_caseless_msbs_mag_Tracer",30],[],""],[],["hgun_Pistol_heavy_01_green_F","muzzle_snds_acp","acc_flashlight_pistol","optic_MRD_black",["11Rnd_45ACP_Mag",11],[],""],["U_I_E_Uniform_01_coveralls_F",[["ACE_packingBandage",25],["ACE_tourniquet",4],["ACE_morphine",6],["ACE_Flashlight_KSF1",1],["ACE_MapTools",1]]],["V_CarrierRigKBT_01_heavy_Olive_F",[["MineDetector",1],["ACE_DefusalKit",1],["ACE_wirecutter",1],["ACE_EntrenchingTool",1],["ACE_M26_Clacker",1],["DemoCharge_Remote_Mag",4,1],["AMP_Breaching_Charge_Mag",2,1]]],["B_Carryall_eaf_F",[["30Rnd_65x39_caseless_msbs_mag_Tracer",9,30],["SmokeShell",5,1],["HandGrenade",2,1],["APERSMineDispenser_Mag",2,1]]],"H_HelmetHBK_headset_F","",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""]]};
            default {[]};
        };
        
        ACE_player setUnitLoadout [_layout, true];
    };
};

if (_arsenalType == "CUSTOM") exitWith
{
    if (isNil "TB_fnc_customLayout") then
    {
        TB_fnc_customLayout = {//Not changed for backward comp.
            params ["_rolle"];

            switch (_rolle) do
            {
                case "lead": {[]};
                case "grena": {[]};
                case "sani": {[]};
                case "mg": {[]};
                case "spreng": {[]};
                case "aaat": {[]};
                case "trag": {[]};
                case "dmr": {[]};
                case "pilot": {[]};
                case "sniper": {[]};
                case "spotter": {[]};
                case "jtac": {[]};
                case "arzt": {[]};
                case "rifle" : {[]};
                case "pionier" : {[]};
                default {[]};
            };
        };
    };

    private _layout = [_rolle] call TB_fnc_customLayout;

    ACE_player setUnitLoadout [_layout, true];
};
