name: Arma

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@master
    - name: Validate SQF
      run: python3 tools/sqf_validator.py
    - name: Validate Config
      run: python3 tools/config_style_checker.py
    - name: Check for BOM
      uses: arma-actions/bom-check@master
      continue-on-error: true
    - name: UTF8-Check
      run: echo '! find $GITHUB_WORKSPACE -type f -exec file --mime {} \; | grep -v "charset=binary$" | grep -v "charset=us-ascii$" | grep -v "charset=utf-8$"' | bash
      continue-on-error: true

#  lint:
#    runs-on: ubuntu-latest
#    steps:
#    - name: Checkout the source code
#      uses: actions/checkout@master
#    - name: Lint (sqflint)
#      uses: arma-actions/sqflint@master
#      continue-on-error: true # No failure due to many false-positives

#  build:
#    runs-on: ubuntu-latest
#    steps:
#    - name: Checkout the source code
#      uses: actions/checkout@master
#    - name: Build using HEMTT
#      uses: arma-actions/hemtt@master
#      with:
#        command: build --ci  # no --release due to https://github.com/synixebrett/HEMTT/issues/227

# https://github.com/actions/upload-artifact/issues/3#issuecomment-524442814
# - name: Upload Artifact
#   uses: actions/upload-artifact@master
#   with:
#     name: ace3-${{ github.sha }}-nobin
#     path: '@ace'
